### ISSUE TITLE
routerLink can't set href to components defined in child router

### ISSUE THREAD

**Issue by twhitbeck** [angular/router#104]
I set up an example of this at https://github.com/twhitbeck/nested-router-example.

The `href` for the links to components `one` and `two` are `.undefined/one` and `.undefined/two`.

The problem is that `routerLink` is attempting to build the href url from parent router's `previousSegment` property which isn't set until `finishNavigating` is called.

**Comment by btford** [comment]
Thanks for filing this issue. It's something I'm aware of; #81 shows a test case for this.
