### ISSUE TITLE
Proposal: rename "router-view-port" directive to "router-viewport"

### ISSUE THREAD

**Issue by davidkpiano** [angular/router#112]
I know this touches many parts of the new router, but the separation of the compound "viewport" into two separate lexemes is confusing. In web development and [computer graphics](http://en.wikipedia.org/wiki/Viewport), it is nearly ubiquitously seen as the compound "viewport," and seldom as two separate words.

Furthermore, "router-viewport" linguistically suggests "a viewport of the router", whereas "router-view-port" suggests "a *port of a view* (meaningless) of the router."

**Comment by gkalpak** [comment]
:+1:

**Comment by polyesterhat** [comment]
:+1: these things are important

**Comment by PascalPrecht** [comment]
Hey @davidkpiano! Thanks for open this up. To be honest I fully agree on that one.

**Comment by davidkpiano** [comment]
Much thanks, @btford !

**Comment by afitterling** [comment]
please, could you give me access to your documents repo to update the documentation?
