### ISSUE TITLE
Can a route to partial pages from strings in JSON selections be done easily? No a tags.

### ISSUE THREAD

**Issue by mLaird** [angular/router#114]
I have translation strings in JSON, per angular-translate and I use them in select dropdowns to route to a new partial page. Its things like {"text": "House", "val": "house4Rent"} and {"text": "Casa", "val": "house4Rent"} JSON won't take a tags nor #  It was really time consuming, and the URLs in the command line still do not have the proper format for HTML5, even though I configured for HTML5. The new router needs to work easily with strings out of JSON to route to new partials and keep proper HTML5 URL behavior.

**Comment by btford** [comment]
This doesn't make much sense to me. If you have some id like `"house4Rent"`, you can of course use this to reference a component.

I'm closing this, but if you have more questions feel free to follow up. A working code example might help.

**Comment by mLaird** [comment]
Brian,

Thank you for your review and response to my request for Angular’s  new
router.  Let me try to explain further. I believe the problem is
$routeProvider cannot directly access the reference string to a new partial
page when that string is inside a JSON object, as is used in dropdowns.


I have a multi-page router working using HTML5 routing, but I get strange
looking URLs in the address bar – even though the pages display as expected.
For example, the initial URL when the home page loads is:
http://localhost/angular-oPost/app/index.html  When I select from a
dropdown, it displays the proper partial page and the URL is again OK,
e.g.,  http://localhost/angular-oPost/app/partials/postApartment4Rent



Then when I hit the back arrow, it goes back to the home page, but the URL
is strange, and not referring to home:
http://localhost/angular-oPost/app/index.html#%2Fpartials%2FpostApartment4Rent



If I reload that strange URL, I get the home page, but with the strange URL
continuing to show.  When I hit the forward arrow, I return forward, the
partial page displays, and its URL is OK, as above.  Problem:The strange
URL is not HTML5 and it will be confusing to users.


Seven key facts are numbered below. I believe the problem lies in numbers 5
and 6, which result from the fact that the new partial page is identified
via a string inside a JSON object that the user selects.  I have not found
a way to get $routeProvider to directly access the selected JSON string –
like   .when( insideJSON  ddSelections_en   “postApartment4Rent”,
{templateUrl: . . .} )   I believe this causes the other problems.

1.    1.   In my app file, the route instructions look like:

$locationProvider.html5Mode(true);

$routeProvider

                .when("/", { templateUrl: "input/partials/home.html",

                                                controller:
"SelectLanguageController" }
.when("/partials/postApartment4Rent",
{ templateUrl: "input/partials/postApartment4Rent.html",

                                                controller:
"InputFormController",

                                                controllerAs: "cntrl"} ) //
and so forth for other partial pages



2.      2.  A home partial page inserts into index.html   via  <div
data-ng-view></div>

3.      3.  This home partial has the <a> tags for the other partials, and
they look like:

<a href="#/partials/postApartment4Rent" id="postApartment4Rent"></a>

Documentation for HTML5 routing says the starting #/ is incorrect and
should be just /

 However, nothing loads with <a href="/partials . . .  and I get errors -
no page exists or access denied.  ng-href does not help.

4.      4.  The partial pages start on the first line with the necessary
information, for example:

<div id = "postApartment4Rent" data-ng-controller = "InputFormController as
cntrl">

This matches with your comment that “If you have some id like "house4Rent",
you can of course use this to reference a component.”

5.      5.  The dropdown for page selection has JSON to identify the new
partial pages, for example:

            ddSelections_en = [

                {"text": "RENT:", "val": "postApartment4Rent"},

                {"divider": true},

                {"text": "Apartment", "val": "postApartment4Rent"},

                {"text": "Senior Living unit", "val": "postSLU4Rent"}

             ];

6.      6.  When the “text” is selected, a $watch fires the new partial
page from the newVal,  like so:

    $scope.$watch( 'ddMenuSelected', function( newVal ) {

        if ( newVal && newVal.text ) {

                $scope.newPage = $timeout( function(){

                                function fireClick( node ){

                                                if ( document.createEvent )
{

                                                                var evt =
document.createEvent( 'MouseEvents' );

                                                                evt.initEvent(
'click', true, false );


node.dispatchEvent(
evt );

                                                } else if(
document.createEventObject ) {

                                                                node.fireEvent(
'onclick' ) ;

                                                } else if ( typeof
node.onclick == 'function' ) {


node.onclick();

                                                }

                                }

                                var theNode = document.getElementById(
newVal.val ); //e.g., postApartment4Rent  Comes from factory array of
dropdown translations


                                fireClick( theNode );
},2);


}

 }, true );  //end of $watch()

7.     7.  The HTML for the dropdown button, using angular-dropdown (from
GitHub) has the updatePostDd() function that selects the proper language
for display (#5 above) and fires the click (#6 above) to move to the new
partial page.

<div id="postBox" flex="35" data-ng-controller="PostResidenceController" >

                <button id="postButton" data-dropdown-menu="ddMenuOptions"

                data-dropdown-model="ddMenuSelected"
data-ng-click="updatePostDd();" class="btn-menu">

                {{ 'POST' | translate }}</button>

</div>



In summary, I have researched a lot, and tried many approaches for many
hours, and have not found a way for $routeProvider to directly access a
user selection for a partial page string that resides inside a JSON object,
as would be used in many dropdown implementations.  I believe new
capabilities are needed in the new router. If these capabilities already
exist and I have not found/understood them, then new documentation is
needed.

On Sat, Mar 28, 2015 at 6:14 AM, Brian Ford <notifications@github.com>
wrote:

> Closed #114 <https://github.com/angular/router/issues/114>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/router/issues/114#event-267525775>.
>



-- 



Mike Laird

12 Arbor Creek Drive, Pittsford, New York 14534
mlaird@alum.mit.edu

". . . remembering on both sides that civility is not a sign of weakness,
and sincerity is always subject to proof. Let us never negotiate out of
fear, but let us never fear to negotiate."  - John F. Kennedy
