### ISSUE TITLE
Implied order for which viewport to put component in?

### ISSUE THREAD

**Issue by mlibby** [angular/router#119]
In the Hello example

Router config show the routes being attached to components. Makes sense.
https://github.com/angular/router/blob/master/examples/angular-1/hello/app.js#L14-L16

The index page, however, has two viewports, one "left", one "right".
https://github.com/angular/router/blob/master/examples/angular-1/hello/index.html#L33-L34

How does the router know which viewport to use?

**Comment by PascalPrecht** [comment]
I think this is rather a bug in that example.

**Comment by btford** [comment]
@PascalPrecht is correct – this was an oversight on my part.

**Comment by btford** [comment]
I've decided to throw with an error message if you have two viewports with the same name. This should make it easier to reason about how sibling viewports should work.
