### ISSUE TITLE
Does the new router support a promise resolve for ALL routes?

### ISSUE THREAD

**Issue by rfgamaral** [angular/router#123]
The current 1.x router allows you to define a map of dependencies to be resolved before the controller is instantiated and any of these dependencies can be promises. I'm wondering if the new router will be able to do that, not just for individual routes, but for all of them.

I mean, one global dependency that needs to be resolved for **any** route before the controller is instantiated.

**Why would I need this?**

My team and I have this application dependent on the user context, which is a backend service. We need this service to return the user context before doing anything else with our application. There's no way around it.

Currently, we have a `UserService` which makes a request to our backend service through `$http` and the method that does this returns a promise, of course. We are using `angular.injector` to get an instance of `UserService` and request the data. It's only when the promise is resolved that we manually bootstrap the application. This feels very hackish but we couldn't find another way to solve it.

Having a _global resolve_ promise would probably help solve this issue in a cleaner and better way.

**Comment by FelikZ** [comment]
There is no reason todo a new router without this feature.

I am production angular user since v0.9 and still there is no **beautiful** way to check some stuff before transitions between paths.
In standard router we can use `resolve` param and this is the only option to this. Currently I didn't see even this option in the new router...

**Comment by rfgamaral** [comment]
We didn't use `resolve` because you'd have to do that for **every** route, correct? And if you have a lot like we do, that's just painful to manage.

**Comment by gkalpak** [comment]
How painful can that be ? Just decorate the `$routeProvider` to automatically add one or more "global" resolves to its routes `resolve` object. You put it in one place and then just forget about it. (Do I miss something ?)

**Comment by FelikZ** [comment]
@gkalpak exactly, there is also possible auto generation of this resolves based on the some path params.

**Comment by rfgamaral** [comment]
I'm a little confused, could you guys provide a simple example of what you mean?

**Comment by PascalPrecht** [comment]
@rfgamaral You might want to keep track of #100 

>I am production angular user since v0.9 and still there is no beautiful way to check some stuff before transitions between paths.

@FelikZ Actually, the new router comes with `canActivate`, `canDeactive` and `canReactivate` hooks. However, it's still in development.

**Comment by FelikZ** [comment]
@PascalPrecht nice to here that. Is there any source to read more about that hooks?

**Comment by PascalPrecht** [comment]
http://angular.github.io/router :)

**Comment by rfgamaral** [comment]
Thanks @PascalPrecht :)

**Comment by rfgamaral** [comment]
Does it make sense to keep this issue opened? I can close it if needed (don't know who else has permissions for that).

**Comment by PascalPrecht** [comment]
@rfgamaral you opened it and should therefore be able to close it. Anywho, I can do it for you now :)
