### ISSUE TITLE
refactor: use CFG instead of NFA to recognize routes

### ISSUE THREAD

**Issue by btford** [angular/router#131]
This is a high-level description of an implementation detail and might be totally **boring** unless ur a nerd.

Right now, the route-recognizer library isn't powerful enough to support recursive route definitions. This is because it's based on a NFA (nondeterministic finite automata), and the config language doesn't allow for cycles to be introduced in the state graph. It's pretty awkward to manage a state graph with cycles, but use a context-free grammar (CFG) would make this more natural.

In order to support non-JS language targets, I'd need to rewrite route-recognizer in AtScript anyway, so this "refactor" is mostly "free."

Initially, we can traverse the grammar ourselves, but later we can explore a strategy where we incrementally generate a parser for the CFG if recognizing routes becomes a bottleneck.

[Matt Might](https://twitter.com/mattmight/status/570057831707246592) pointed me towards these resources:

* http://matt.might.net/articles/parsing-with-derivatives/
* http://www.cs.uwm.edu/~dspiewak/papers/derivative-parsing.pdf

This is related to #129.

**Comment by btford** [comment]
On second thought, this isn't really needed.

**Comment by PascalPrecht** [comment]
Haven't even fully understood what the original concern was. But cool this can be closed.
