### ISSUE TITLE
router-link generating URLs with undefined

### ISSUE THREAD

**Issue by dpogue** [angular/router#134]
I'm trying to do nested routes like this:

```javascript
angular.module('landing', ['ngNewRouter'])
.run(function($router) {
    $router.config([{
        { path: '/landing', component: 'landing' }
    }]);
})
.controller('LandingController', function($router) {
    // $router is the child router in this instance
    $router.config([{
        { path: '/signup', component: 'signup' }
    }]);
});
```

This works as expected if I go to `/landing` and `/landing/signup`.

In the template landing.html, I have a link:

```
<a router-link="signup">Create an account</a>
```

At runtime, the href for this link is `"http://localhost:8000/landing/.undefined/signup"` and clicking it does nothing.

If I use the browser console to change the href to `"landing/signup"` it works as expected.

The nested routes are working properly, but apparently it is impossible to generate links to them with the router-link directive.

**Comment by btford** [comment]
This is a duplicate of #104

**Comment by dpogue** [comment]
Thanks, I'll close this to avoid confusing duplicate tickets.
