### ISSUE TITLE
Specifying a viewport results in weird route names

### ISSUE THREAD

**Issue by dpogue** [angular/router#135]
```javascript
angular.module('test', ['ngNewRouter'])
.run(function($router) {
    $router.config([{
        path: '/foo',
        component: {
            master: 'foo'
        }
    }]);
})
```

The resulting route is registered with the router as `[object Object]` because component isn't a string.

`$router.generate('foo')` returns `""`.
`$router.generate('[object Object]')` returns `"/foo"`.

**Comment by PascalPrecht** [comment]
Hey, i'm currently on mobile so i'm just making a guess based on your code
you've posted here. In your code in your Router configuration, change
`component` to `components`. Looks like a typo.

Does that help?

**Comment by dpogue** [comment]
I tried using `components` and that didn't seem to work at all. Looking through the code, it handles a bunch of different types of `component`, but the only place I've seen `components` is in the docs (which at this point, I'm assuming is a typo).

https://github.com/angular/router/blob/master/src/router.ats#L78-L86

**Comment by btford** [comment]
This should now be fixed in master; both `component` and `components` do the same thing.

Sorry for the confusion!
