### ISSUE TITLE
feat(1.x): HTML5 mode by default

### ISSUE THREAD

**Issue by btford** [angular/router#147]

**Comment by btford** [comment]
On second thought, I'm not totally sure I like this having a config block in this module that overwrites defaults. It introduces an ordering constraint depending on how scripts are added/catenated.

@IgorMinar – I think you suggested this. Thoughts?

**Comment by SanderElias** [comment]
@btford I agree with you. A better solution would be to change the default in angular. This can be then documented as a breaking change. It will have little impact on existing apps, but it will pave the way forward for new apps. Perhaps this can be done on the 1.5 milestone?

**Comment by btford** [comment]
Closing this in lieu of https://github.com/angular/angular.js/issues/11451
