### ISSUE TITLE
nested routes path / sub components??

### ISSUE THREAD

**Issue by schmitch** [angular/router#151]
Hello,
I'm writing this, since I am really confused.

Currently I have the following issue,
I have a app with something like a component called ```/article```
And now I have a subrouter that routes to my next component, lets call it ```/list```
so far so good, but now, when I call it, it looks for list inside /components instead of /article/components.
Which is really odd, since the subrouter is useless if it is a big app, since i would trash my components folder completly, also it isn't really reusable if i need to copy sub components into my components folder??

Oh and I currently solved it by speciying a ```$componentLoader``` in the component configuration. but that is really really odd.

Oh and here is my quick fix so you can specify components as 'component/subcomponent':
```
  .config(['$componentLoaderProvider', function($componentLoaderProvider) {
    function dashCase(str) {
      return str.replace(/([A-Z])/g, function ($1) {
        return '-' + $1.toLowerCase();
      });
    }

    $componentLoaderProvider.setTemplateMapping(function (name) {
      if (name.indexOf('/') !== -1) {
        var part = name.split('/');
        return './components/' + dashCase(part[0]) + '/components/' + dashCase(part[1]) + '/' + dashCase(part[1]) + '.html';
      } else {
        var dashName = dashCase(name);
        return './components/' + dashName + '/' + dashName + '.html';
      }
    });

    $componentLoaderProvider.setCtrlNameMapping(function(name) {
         if (name.indexOf('/') !== -1) {
           var part = name.split('/');
           return part[1][0].toUpperCase() + part[1].substr(1) + 'Controller';
         } else {
           return name[0].toUpperCase() + name.substr(1) + 'Controller';
         }
    });
}])
```

Just needed to put it into the main config of the Application

**Comment by schmitch** [comment]
Closed since there is already an issue

**Comment by jvandemo** [comment]
Hi @schmitch,

Components live on the same level in the `components` directory.

For example:

```
└── components
    ├── header    
    ├── homepage
    ├── footer
    ├── login  
    └── portfolio
```

so the default behavior of the component loaders is to load your components from the `components` directory.

This is conform the "[Best Practice Recommendations for Angular App Structure](https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub)".

**Comment by schmitch** [comment]
> Components can have subcomponent directories, including appended naming where possible.

So...

**Comment by jvandemo** [comment]
Not sure if a recursive approach is recommended for the web (as opposed to e.g. in node).

Suppose you have:

```
/components/a/components/b/components/c/components/d
```

If you take into account lazy loading via `$http` then you would have to look for a component template in:

```
/components/a/components/b/components/c/components/d/components
/components/a/components/b/components/c/components
/components/a/components/b/components
/components/a/components
/components
```

before knowing if it exists or not.

I think that's why a flat structure is implemented by default, but you can implement your own strategy if you project requires it (as in your case).

Does that make sense?

(This is just my thoughts, would need @btford 's input to be sure my reasoning is correct).

**Comment by schmitch** [comment]
the thing is the second time writing components is maybe a little bit too much so 
```
/components/a/b/c/d
/components/a/b/ c
/components/a/b/ 
/components/a/
/components/b/e/f/g
etc...
```

Should be enough.
also lets take a look at the most sites they always have a recursive approach. we always have and will have some sites where we first klick on a link and get a list, if we click on the next thing some details will open. but it is still the same component since the detail is attached directly to the list, if we now have a second site it will have a diffrent component. 
Let's use CRUD for example.
Maybe we have a Model Books and maybe a Guestbook model, so now we have two different components, and each component have some sub components that only makes sense in their component.

flat structure is fine, if our application only has one thing to do. Like Email without contacts, but once we need to change contacts and need to edit them, etc.. than we will struggle with that model.
i know angularjs will do a lot more things for mobile first, where flat is good, but in the real world there are still some applications that don't have mobile first, or don't use that model.

And I think that angularjs is great for big projects, but big projects needs to be supported, else we still need our ui-router or our segment-router, etc..

Also in the current state the subrouter still have a lot of bugs.
