### ISSUE TITLE
Provide mechanism to specify controller/template mapping in the place routes are defined.

### ISSUE THREAD

**Issue by hannahhoward** [angular/router#154]
Hi, I've been looking over the code for the new router, coming from a ui-router background. I can see the use of conventions for mapping components to templates and controllers, but it also feels very limiting not to be able to configure these. I've now located the $componentLoaderProvider service, but specifying these mappings in a single global function far away from the place you map components to routes feels cumbersome, and may lead to a lot of confusion when the mappings are not obvious to someone looking at the router configuration code. I'd like to implement an alternate interface that allows you do do something like this: 

$router.config([
    {path: '/', component: 'componentName', controller: 'SomethingController', template: 'SomeTemplate' }
  ]);

or alternatively:

$router.config([
    {path: '/', component: { controller: 'SomethingController', template: 'SomeTemplate' }
  ]);

Among other things, this would make ui-router transitions much easier. Happy to implement it myself but I'd prefer to know it's something the team is open to first before I put in the effort.

One other suggestion you don't want to pollute the $router interface: provide an alternative service like '$componentMapper' that has an interface like:

$componentMapper.map({
        'componentName': { controller: 'SomethingController', template: 'SomeTemplate' }
})
(could be called multiple times in separate places so that component mappings stayed near router configuration)
Admittedly I think this could be implemented as an addon atop the existing $componentLoader functionality.

Not sure if this is a duplicate of https://github.com/angular/router/issues/99

**Comment by jvandemo** [comment]
I think this is being addressed in #127 (see proposal in the thread).

**Comment by btford** [comment]
@jvandemo is correct – This is something I want to do, it's just a question of how best to support it.

I'm going to close this issue, and we can continue discussion in #127. Thanks!
