### ISSUE TITLE
redirectTo is not working

### ISSUE THREAD

**Issue by nareshbhatia** [angular/router#155]
I am not sure if `redirectTo` is working yet. When I run the hello example by pointing my browser to `http://localhost:8000/examples/angular-1/hello/` I expect that the router would redirect to `/welcome`, but that does not happen. All I see is the 3 links shown by `index.html` and I have to click on the `welcome` link to go to the welcome page.

**Comment by schmitch** [comment]
That's a problem caused by html5mode. you can either append an # to your url or just try the example in a html5mode enabled webserver.

**Comment by nareshbhatia** [comment]
I tried the following, but it does not work:

    function AppController($router) {
        $router.config([
            { path: '/',              redirectTo: '/#/welcome' },
            { path: '/welcome',       component: 'welcome' },
            { path: '/flickr',        component: 'flickr' },
            { path: '/settings',      component: 'settings' }
    ]);

Also, I feel that this is not very intuitive. If all the "path" attributes do not have # in them, then it only makes sense for redirectTo to not have it. The framework should be able to adjust to the html mode.

**Comment by schmitch** [comment]
No you need to append a # at your browser url..

**Comment by nareshbhatia** [comment]
Ah, thanks. This now works:

    http://localhost:8000/examples/angular-1/hello/#/

I think the example is great to show how redirectTo works, but to avoid any confusion, I would rather just make / my welcome page:

    function AppController($router) {
        $router.config([
            { path: '/',              component: 'welcome' },
            { path: '/flickr',        component: 'flickr' },
            { path: '/settings',      component: 'settings' }
    ]);

But that's just my personal taste!

Thanks again for your help.
