### ISSUE TITLE
chore: choose an awesome new name for the routing system

### ISSUE THREAD

**Issue by IgorMinar** [angular/router#159]
EDIT (by @btford) to summarize the current contenders:

* ComponentRouter (+9)
  - - very long, doesn't really roll off the tongue
  - + component all the things
  - + current favorite by popular vote
* Acute Router (+4)
  - + cute name
  - + easy to say
  - - serious connotation in medicine, psychology (e.g. acute anxiety)
* ngRouter (+2)
  - - too similar to `ngRoute`
* ViewTeleporter (+2)
  - + fun
  - + nothing in angular called "teleporter" yet
  - - too many things called "view"
* ViewRouter (+2)
  - - too many things called "view"
* The New Router
  - - the word "new" is confusing and bad
* Navigator
* Composer
  - - there is already a popular open source PHP project with this name
  - - doesn't really evoke "routing"
* ScreenRouter
  - - might be conflated with "screen reader"
* ComponentTeleporter
* Route 66
  - - Other open source projects with this name exist
* RouteDiviner
* Vector (Router)
* Scenic (Router)
* Segue (Router)

The (+x) refers to the number of popular votes. The final decision will not necessarily be the most popular option, but it'll definitely be a large part of the consideration.

---

Several folks have voiced a concern about the ambiguous name that this project currently uses: "The New Angular Router" / `angular-new-router` / `ngNewRouter`

The problem with "new" is that it's not a great keyword (lots of search conflicts) and it won't stand the test of time.

There are several other names being proposed by various community members like: Navigator, Composer, ViewRouter, ngViewRouter, ScreenRouter, or ViewTeleporter (my creation :-)).

It would good to have a discussion about this and maybe even crowdsource the problem.

Please make sure that @shairez approves of the name, so that we can avoid another ng-wat :-D

**Comment by btford** [comment]
What does this look like in code (module name, `npm install {{name}}`,
etc.)?

**Comment by gkalpak** [comment]
:+1: For a better name.

:-1: :-1: :-1: For trying to avoid another ngWat !

**Comment by jvandemo** [comment]
:thumbsup:

Personal suggestion: **Component Router**.

#### Motivation

- it's what the router actually does: associate url's with a map of viewports and components
- refers to the future of web components
- keeps it easy to spell: `component-router`, `componentRouter`

**Comment by benmj** [comment]
+1 for ComponentRouter @jvandemo

**Comment by wardbell** [comment]
I like ViewRouter because it has the word "Router" in it (both searchable and expected) and it routes to what everyone thinks of as a "View" (or views). It also recalls the new "ViewPort" term and is easy to say.

Navigator is cool (not as cool as teleporter) but is unexpected.

"Component" is interesting. It suggests that the router is a "ViewModel First" approach to routing and composition. Unfortunately ( imo as a VM first fan), I don't think that is true; the router retains it's "View First" orientation. I'm long since used to losing that battle so np. The other problems:  "Component" is a three-syllable mouthful and just sounds ugly :-)  and I doubt it fits the majority's mental model of router behavior. Kudos, though, for the concept.

**Comment by petebacondarwin** [comment]
`ngRouter-2`?

**Comment by petebacondarwin** [comment]
Router-66?

**Comment by btford** [comment]
I definitely think we can do better as far as a name, but the name needs to be demonstratively better than "The New Router."

I agree that the new name should include "router." It's an industry standard term, it's what people will search for, and I'm guessing developers will use that verbiage regardless of what we name it.

Names that include "2" are out, because we're going to be closely following semver. "Router2 v3.0.1" would be really confusing.

I'm not too fond of "ScreenRouter;" I think it sounds too much like "Screen Reader." But I'm not too opposed to this if others like it.

"ViewRouter" is a bit confusing, because the term "view" is already so overloaded. I think we should avoid it.

"ComponentRouter" seems okay.

**Comment by ChrisPearce** [comment]
I like ComponentRouter.

Or for something more generic "ApplicationRouter"?

**Comment by shairez** [comment]
@IgorMinar you really do "listen to reggae music" if you think I only have stuff about bad naming for my next ng-wat :)

What about RouterRouter? 
it has 2 of those in it, so it could represent ng "2" 
and it follows the same conventions we're used to ;)

But seriously, I also liked componentRouter, although it will probably be more of a composition of components' state, it is still a good base name IMHO, and it could cover individual reusable components + applications (if it make sense)

**Comment by wardbell** [comment]
@btford  Why is "component" less confusing than "view"? Could there be a more generic term than "component"? That's just a small step from "thing" :-)

I imagine that those who favor "component" do so because that concept is fundamental to the new router. I'm looking at an example configuration from your [phone-kitten sample](https://github.com/angular/router/blob/master/examples/angular-1/phone-kitten/app.js):

    $router.config([
        { path: '/'                , redirectTo: '/phones'    },
        { path: '/phones'          , component: 'phoneList'   },
        { path: '/phones/:phoneId' , component: 'phoneDetail' }
    ])

The ***word*** "component" is indeed prominent. But is the ***concept*** active as well? 

It would seem so. If I understand correctly (w/o aid of documentation), the term 'phonelist' invites the router to apply conventions that would marry the [*phone-list.js* component](https://github.com/angular/router/tree/master/examples/angular-1/phone-kitten/components/phone-list) to the *phone-list.html* view. It is fair to say that this is a "ViewModel First" approach that emphasizes the role of the component (the VM) in the equation. 

>This despite other examples (e.g., [sibbling-routes](https://github.com/angular/router/tree/master/examples/angular-1/sibbling-routes)) that demonstrate a purely "View First" routing configuration with no component in sight.

**Therefore**, I see virtue in the term "ComponentRouter" even if saying it out loud makes me cough up a lung.

Consider that the mildest possible endorsement of "ComponentRouter" should "ViewRouter" fail to make the cut.

**Comment by davej** [comment]
+1 for ComponentRouter.

**Comment by btford** [comment]
> Why is "component" less confusing than "view"?

There are fewer things named "view" than "component" – but maybe that'll change. I already will need to change "ng-viewport" (at least for Angular 2) since the new view system already has its own notion of "viewport."

>  That's just a small step from "thing"

Point taken.

**Comment by SanderElias** [comment]
@btford @wardbell @shairez hmm, going over this thread, I came to like "ngRouteAllTheThingiesRouter" ;)

+1 for ComponentRouter

**Comment by gkalpak** [comment]
Apart from being only one letter away from `ngRoute`, is there anything else inherently wrong with simply `ngRouter` (it's very conveniently generic) ?

<sub>Or maybe just PORS (**P**lain **O**ld **R**outer **S**ervice) ?</sub>

**Comment by SanderElias** [comment]
@gkalpak The old router will stay inside the 1.x branch, It will be very error-prone to be 1 letter off the old router. Not to mention the confusion it will cause.

**Comment by jelbourn** [comment]
I also like ComponentRouter since it jives rather nicely with the new API in v1 and how it will work in v2.

**Comment by rathishc24** [comment]
+1 for ComponentRouter

**Comment by PatrickJS** [comment]
My honest vote is **ViewTeleporter** from @IgorMinar for these reasons. 
- It's fun: Remember when we used to call angularjs the superheroic framework? That was fun.
- It's honest: We're working with views no matter what environment is mobile/cars/server.
- It's exciting: Everyone wants a teleporter (seriously who wants to waste time walking).
- It's not too serious: Again being fun while being different at the same time.
- It's actually very clear: You don't question it. It's a teleporter and you're dealing with views.
- It's using the correct term View: using view and router tends to be a dead horse 
- It's not locked into one framework: There is no ng prefer as much as we all love to ng everything

With marketing names like Ember, Glimmer, Relay, Flux, and of course Angular. Why is it that every time a framework comes out the router name remains the same boring variation. 

Sidenote: With a name like ComponentRouter you are strongly implying the component/router convention which may change in the future

[![Tipe CMS](https://user-images.githubusercontent.com/1016365/34912701-7edec34c-f89c-11e7-8c89-bed6cef064b5.png)](https://tipe.io?ref=github-comment)

**Comment by petebacondarwin** [comment]
Router!

**Comment by petebacondarwin** [comment]
As in the English pronunciation :-)

**Comment by butchpeters** [comment]
Routetacular? ;)

**Comment by dcunited08** [comment]
Is angular 2.0 going to be namespaced angular2 (bower install angular2 angular2-router angular2-animate) or will it just be angular 2.0 and you must specify the version?  I like the componentrouter the best but it is somewhat long.  Would you want to have the same name across both versions or would you release version-specific packages to npm and bower?

**Comment by wardbell** [comment]
@petebacondarwin We had your back buddy ... a thorough vetting of "rooter" ... "rootrooter" and all the connotations and malapropisms we could find made spirited rounds by email. Naturally it has a snow ball's chance of escaping into the wild.

@butchpeters Kudos for "Routetacular"!  A fond memory indeed.

**Comment by codef0rmer** [comment]
How about?

Old : `ngRoute`
New : `ngRouter`

**Comment by skusunam** [comment]
ComponentRouter (or) ngRouter. It is hard to think of anything without "ng" and i know what is coming in Angular-2 :)

**Comment by btford** [comment]
What about "Acute Router?" I like it because it's also an acronym for "a cute router" and cute things are good. It also evokes "angular" with the related geometric term, but without making it seem tied to Angular 1 or Angular 2.

**Comment by alexeagle** [comment]
brainstorming

* routy
* routeular
* rerouter
* rotorooter (copyright problems?)
* rooter
* route66

**Comment by caitp** [comment]
"acute" is also good because it's sharp and edgy (much better than "obtuse router"!)

**Comment by btford** [comment]
@alexeagle thanks for the suggestions.

Among those, I like route66 best, but it seems like there are already half a dozen tiny projects using the same name. I wouldn't be comfortable using it without reaching out to all those authors first.

**Comment by tynman** [comment]
+1 for "acute". Rather clever name! I'm surprised no other projects are using it. Sticking with angles, there are also "oblique", "tangent", and "right" angles. "Right Router" may sound presumptuous, but it's a good play on words too.

**Comment by gnomeontherun** [comment]
+1 ComponentRouter 

I don't care if its long, I prefer it to be clear than cute/fun/concise.

**Comment by themihai** [comment]
nrouter, nroute, n-router:  routes n routes. 
``npm install nrouter``

**Comment by ggoodman** [comment]
How about `RouteComposer`?

**Comment by SiegfriedEhret** [comment]
Users follow components/views. Cows follow grass.
How about "Brouter" ? Brouter is the french word for "chew grass".

**Comment by jough** [comment]
+1 for ngRouter. I'm sure a lot of things will have similar names to 1.0 and that shouldn't stop us from naming something the most appropriate and easy to remember name.

**Comment by kegluneq** [comment]
+2 Acute Router
+1 ComponentRouter

**Comment by bpotaczek** [comment]
How about Vector staying with the geometry theme.

**Comment by crissdev** [comment]
Why not use the same name and bump the version `2.x`? I'm pretty sure `angular v2` won't need a new name.

**Comment by thejones** [comment]
Escape Route

**Comment by btford** [comment]
@bpotaczek – I like it!

@crissdev – it's a totally different codebase, and conceptually very different. I think using the same name is too confusing.

**Comment by petebacondarwin** [comment]
BikeShedRouter!

**Comment by ChrisPearce** [comment]
Some more alternatives:
RouteActivator
RouteDiviner

**Comment by petebacondarwin** [comment]
Routavator

**Comment by lgalfaso** [comment]
Router<sup>2</sup>

**Comment by petebacondarwin** [comment]
Router++

**Comment by petebacondarwin** [comment]
Router#

**Comment by petebacondarwin** [comment]
SharpRouter

**Comment by ChrisPearce** [comment]
Pathway

**Comment by Munter** [comment]
Scenic

**Comment by sarod** [comment]
Segue

**Comment by btford** [comment]
> Routavator

Seems like a bad pun.

> Router++

IMO, just as bad as naming it "New Router"

> Router#

Oh! What about Router♭? I jest. I think names that include non-alphanumeric characters are out, because they make naming conventions more confusing.

> SharpRouter

Seems like a less cute version of "Acute Router"

**Comment by btford** [comment]
> Scenic

:+1: 

> Segue

:+1:

**Comment by JasonRodman** [comment]
ngRouting

**Comment by Brocco** [comment]
Brainstorming:
ClientUri - **ClientU**_niveral_**R**_outing_**I**_nterface_
Usher - it directs you through the application?
Sherpa or ClientSherpa

**Comment by ElliotPsyIT** [comment]
'acute' has a clever association for the mathematicians, but has a distractingly serious connotation for us psychologists (acute anxiety) :)

stateRouter

**Comment by devorbitus** [comment]
RouteTransporter

**Comment by davidkpiano** [comment]
+1 Vector, though searching for "Angular Vector" might be confusing.

+1 ComponentRouter as well.

**Comment by himansudesai** [comment]
Why should there be anything longer or allegedly more descriptive/expressive when ngRouter is already the perfect name?  Ember Router, React Router... AngularRouter (ngRouter).  This *should* withstand the test of time - no?  There may be different versions of Angular and possibly different semantics but for a given version, it is still 'the router'.

**Comment by mogadget** [comment]
PathRoute
theRouter

**Comment by btford** [comment]
@ElliotPsyIT – Do you think this is "triggering" for those afflicted? I don't want to trivialize serious medical conditions, but my gut feeling is that in this context, "acute" wouldn't evoke the medical definition. I'm not the expert though – what do you think?

**Comment by zsims** [comment]
If it's going to be namespaced differently in ng2, then the same name it has now. Otherwise ComponentRouter or ViewConductor.

**Comment by billfranklin** [comment]
ngTranspath ngConcourse

**Comment by Yonet** [comment]
+1 ViewTeleporter

**Comment by Mayho** [comment]
+1 stateRouter

**Comment by rixrix** [comment]
+1 ComponentRouter

**Comment by jeffwhelpley** [comment]
@Mayho stateRouter would be extremely confusing because the router does not do anything with states. Perhaps it will change in the future, but right now it is completely URL driven and each router is independent from one another. Which is why many people are suggesting ComponentRouter. The scope of the routing is at the component level.

+1 ComponentRouter

**Comment by petebacondarwin** [comment]
@jeffwhelpley - this is a very good point and so how about `UrlRouter`? This is a serious suggestion compared to some of my previous ones.

**Comment by rixrix** [comment]
@petebacondarwin `UrlRouter` would probably be my second choice and it does reflects to what @jeffwhelpley was saying... 

hmmm +1 UrlRouter

**Comment by jeffwhelpley** [comment]
@petebacondarwin Yeah, I actually I would agree with that. The only thing I would caveat with this and my previous comment is that while this accurately describes the current state of the router, it does artificially limit what it can do in the future. Basically, if the thinking is that this is all the router will ever do, then I would change my vote from ComponentRouter to UrlRouter. However, if there are plans to expand to do full state management (i.e. just like the UI Router), I would like a more generic name like ViewTeleporter (as argued by @gdi2290).

**Comment by rainboxx** [comment]
@btford @ElliotPsyIT I needed to lookup the exact meaning of "acute" and the medical meaning came first (New Oxford American Dictionary).

+1 for ComponentRouter

**Comment by patcito** [comment]
Pizza, cause we all love pizza. PizzaRouter, there you go.

**Comment by caitp** [comment]
who can argue with PizzaRouter?

**Comment by PatrickJS** [comment]
+1 PizzaRouter

[![Tipe CMS](https://user-images.githubusercontent.com/1016365/34912701-7edec34c-f89c-11e7-8c89-bed6cef064b5.png)](https://tipe.io?ref=github-comment)

**Comment by jvandemo** [comment]
Locomotive

- loc: short for location url
- com: short for components
- motive: by definition is a cause that induces an action

Locomotive maps location url's to components and induces actions.

Motive is also a concept in mathematical geometry.

**Comment by jvandemo** [comment]
Acute has a bit of a negative context here in Europe. It is mostly used in a context where an urgent action is needed due to an emergency or sudden disease.

**Comment by msafi** [comment]
Problem with Component Router is that it's confusing to me. To me components make up a view, so how can a router be per component when I have multiple components in one route?

I like Route 66 because it has no connotations and I can approach learning it with an open mind without trying to understand it just by reading its name.

**Comment by dfkaye** [comment]
BikeRoute. 

 Or TrafficCop.  Or Dispatcher. 

Or ng<AnyOfThese>

**Comment by vlazar** [comment]
__anroute__ (Angular + enroute)
or just __enroute__

bonus point: no anroute.js or enroute.js yet

definition:
during the course of a journey; on the way: he stopped in Turkey en route to Geneva.
ORIGIN late 18th cent.: French (see route) .

**Comment by vlazar** [comment]
ruter (ruter.js in use)
ruuter (ruuter.js in use)
rauta
router

**Comment by petebacondarwin** [comment]
http://en.wikipedia.org/wiki/Rutabaga

![image](https://cloud.githubusercontent.com/assets/15655/6914330/2243fc86-d781-11e4-8738-a84259f28d00.png)

**Comment by gkalpak** [comment]
Let's be honest with ourselves. Nothing will be as good as ngRouter. :disappointed: 

Maybe we should just rename `ngRoute` to avoid confusion (or we'll have that empty void inside for ever (at least until ngRouter 3.0 is out)).

How about:
`ngRoute` -> `ngVeryBasicButStillGoodEnoughRouting`
or
`ngRoute` -> `notNgRouter` (100% "confusion-proof" - as explicit as it can get)

**Comment by jvandemo** [comment]
**Angular Router**

Just plain, simple.

#### Motivation

- Uses *Angular* instead of *AngularJS* so is in line with the new Angular logo
- Is non ambiguous in a sentence, even for people that do not know about Angular: "you can use Angular Router to map components..."
- GitHub repo name can stay as it is: `angular/router`

**Comment by davidkpiano** [comment]
+1 **Angular Router** - easily searchable and adequately distinguishable from `ngRoute`.

**Comment by kpgarrod** [comment]
RoutAngular

**Comment by ElliotPsyIT** [comment]
@btford - I wouldn't be surprised at brief emotional discomfort especially those with current or recent difficulties.  In general, I'd want to avoid any term with a pretty commonly used clinical reference like 'acute'

**Comment by SanderElias** [comment]
@btford Hmm, I have to agree with @ElliotPsyIT, the emotions people will have by the work acute will seldom be positive. There are a lot of acute <blank> things that you don't want to experience, and if you had one, you probably could do without a reminder.  That's too bad, because at first sight I liked aCute router.
Sooo routitus is out too ;)

how about AnRoute(r)? An can stand for Angular, but it can also mean, on the route(r), or even simply been read as A route(r)

**Comment by bradlygreen** [comment]
+1 for ViewRouter.

But if we're going whimsical, you really can't do better than Rutabaga. :D

**Comment by PatrickJS** [comment]
+1 BikeSheddingRoute

[![Tipe CMS](https://user-images.githubusercontent.com/1016365/34912701-7edec34c-f89c-11e7-8c89-bed6cef064b5.png)](https://tipe.io?ref=github-comment)

**Comment by willbuck** [comment]
I'll throw another suggestion in:

**RouteTeleporter**

+ keeps the fun 'teleporter'
+ maintains having 'route' in it for searchability
+ Stays away from *View* and *Component*, which are causing contention and are admittedly overloaded terms
- Perhaps not the clearest or too silly

I could get behind StateRouter, ViewRouter or ComponentRouter, though I must say of those three 'front-runners' **I prefer ViewRouter**. I think of routing to views, perhaps that's an antiquated notion but that matches my mental model best. I think of State and Components much more as finer-grained programming constructs.

**Comment by gkalpak** [comment]
ngSpaceBridge or ngWormHole (for extra "future-proof-ness")

**Comment by danwkennedy** [comment]
DialingComputer?

**Comment by SanderElias** [comment]
hmm, just did an reread of the entire tread, Bikeshedding 101!, we all just seem to love that :)

I will change my vote, as long as we are busy with this, lets play the game!

Vector :+1: :+1: :+1:  A vector points to somewhere, and it can point to anything, including states,, components and just plain old templates. it's different enough, and it's catchy. that, plus all the things that are said about it before.

ComponentRouter, I'm not so sure anymore, I think a router should not be linked to components only. Still like the sound of it.
The same goes for viewRouter, Sounds good, but it seems limiting.
I won't go over the entire list, but most have issues like the ones I just mentioned. 
Another few sound nice, but have (next to) nothing to do with routing(as in pointing an app to some point, hey doesnt that sound like a vector to you?)

**Comment by sarod** [comment]
bifrost as a superheroic way to go from one place to another?

**Comment by rhalff** [comment]
Switch?

**Comment by himansudesai** [comment]
Agreed!  The whole discussion is about "what should we now call ngRouter?"
It means it already has a name.  Many of the creative names suggested, miss
the mark and require a paragraph to justify the new name for ngRouter.

On Tue, Mar 31, 2015 at 3:53 AM, Georgios Kalpakas <notifications@github.com

**Comment by dcunited08** [comment]
@jvandemo I think Angular Router is too close to Angular UI Router.  In order to find examples you would have to search 'angular router -ui' or by date.

**Comment by tapas4java** [comment]
How about `ng2-Route` or `ng2Route`??

**Comment by tapas4java** [comment]
Or may be `ng2Router`

**Comment by kevinfairclough** [comment]
Some suggestions

Angular Weave
Angular Wire

**+1 ComponentRouter**

**Comment by armorik83** [comment]
+1 for ComponentRouter.

**Comment by Quramy** [comment]
+1 ComponentRouter

**Comment by Simon-Li** [comment]
+1 for ComponentRouter @jvandemo

**Comment by rathishc24** [comment]
+1 AngularRouter
+1 ngRouter
+1 ComponentRouter

**Comment by tommck** [comment]
AtRouter? ;-)

**Comment by himansudesai** [comment]
:+1: ngRouter

**Comment by btford** [comment]
We're going with ComponentRouter by popular vote. Thanks for playing everyone! :bike: :house:

**Comment by timjacobi** [comment]
With Angular 2 generally dropping the *ng* I vote for *Angular Router*. Everything else would just give me the feeling that the router has been written by someone else but the Angular team.
