### ISSUE TITLE
Provide Support for changing of the components folder location

### ISSUE THREAD

**Issue by darcnite3000** [angular/router#165]
can we adjust thing such that the location that is looked for for the components is easily modifiable without remaking the dasherization code

ie so that it could look in /dist/compenents/ or /app/components

**Comment by vlopez5** [comment]
+1 - I would use this feature

**Comment by SanderElias** [comment]
@darcnite3000 @vlopez5, Yes you can,  by supplying a custom `$componentLoaderProvider`
However, I think this should be a little less complex.

**Comment by btford** [comment]
I agree this is something we want to support.

There's already a similar thread in #127 for this, so I'm going to close this as a duplicate. Please continue discussion on #127. Thanks!

**Comment by btford** [comment]
Agreed. I definitely want a better API.
