### ISSUE TITLE
Consider allowing the router to load a Polymer Element / Web Component

### ISSUE THREAD

**Issue by dotDeeka** [angular/router#169]
I will be starting an Angular 1.4 project soon and I am considering using Polymer for many of the reusable pieces of my application. Would it make sense to allow the router to load a Polymer Element?

How different are Polymer Elements, Web Components and Angular 2.0 Components? Would this change be feasible for 1.x?

**Comment by btford** [comment]
Conceptually, this is the same as #161 – going to close this as a duplicate.

The New Router can't really do as much to improve the situation for WebComponents in Angular 1, but if you've wrapped a WC in an Angular 1 directive, Angular will know how to interact with it.

**Comment by dotDeeka** [comment]
Thanks, sorry for the dup.

**Comment by btford** [comment]
No worries; it's a non-obvious dup.
