### ISSUE TITLE
Listening for routing changes for authentication related redirections

### ISSUE THREAD

**Issue by ChrisPearce** [angular/router#170]
In my existing application (that is using the old ngRouter) I have been listening to the $routeChangeStart event to redirect users to the login page when they are not already signed in.

The basic logic consists of the following steps: 
* intercept each routing call by listening for the $routeChangeStart event (registered via a run operation on the top level Angular module)
* check whether the user is authenticated (using my custom Authentication Service)
* redirect the user to the login page (if they are not authenticated)

I note that at the controller level I can use the "activate" hook of the component/controller lifecycle to implement similar logic. However, it appears that this will require adding the logic to each controller/component.

Is this the intended approach for authentication or are there any application wide events exposed by the new router that could be used to achieve a redirection for unauthenticated users?

**Comment by dpogue** [comment]
I worked around this using ES6 classes and making a base class that checks authentication in canActivate. All my app controllers extend that base class.

**Comment by ChrisPearce** [comment]
Many thanks @dpogue. Your approach of using a base class for the controller provides a working solution to the problem.

However, it does mean having to adopt an inheritance strategy for the controllers to implement what I believe is a common authentication use case. If there was an application wide event available I believe it would allow us to make the structure of authenticating applications simpler.

**Comment by SanderElias** [comment]
related and possible duplicate of #33

**Comment by btford** [comment]
I think listening for global route change events is an anti-pattern.

I think a better way is either like @dpogue describes, or using mixins, or by adding a step to the navigation pipeline (more on this soon).

**Comment by btford** [comment]
I'm going to close this is favor of #33 – let's continue discussion there.
