### ISSUE TITLE
Support for server rendered initial content

### ISSUE THREAD

**Issue by manikantag** [angular/router#172]
Hi,

Does the New Router supports state changes after initial server rendering?

Use case: Instead of keeping the user wait till all the scripts loaded*, I wanted to render some content in the ng-view/ng-viewport section, say 'Home' content. And once the complete SPA is bootstraped, and when user clicked different link which has different route, I want to override the 'Home' content with that route specific template. And, when user clicks 'Home' again, now I want the server rendered content to be shown. With old(?) router, it is not easy to do that without cashing the contents manually before the route change. This will also serves as partial solution for newly coined 'Isomorphic way' of building SPA (http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/, http://augustl.com/blog/2014/jdk8_react_rendering_on_server/, http://berzniz.com/post/99158163051/isomorphic-javascript-angular-js-is-not-the). Partial in the sense, only index/home page will rendered by server and other routes will be shown/compiled by AngularJS. This way critical rendering can be achieved (https://developers.google.com/web/fundamentals/performance/critical-rendering-path/).

*Loading all scripts can be avoided once the new proposal for lazy loading is released: https://github.com/angular/angular.js/issues/11015.

*https://github.com/angular/router/issues/152 seems similar issue to me.*

**Comment by btford** [comment]
Angular 1 does not have first-class support for server-side rendering, but there are some tools that add this capability. If any of the authors of this tool are interested in helping inform the design of the router, I'm happy to get their feedback.

Angular 2 is designed to split things apart so server side rendering is possible, but it's still up in the air whether it'll support it.

There are a few design considerations that make route config easily statically analyzable so that if server-side rendering is supported, it'll be easier to implement.

Regardless, this isn't something the router has control over – it's more a question of the templating system in Angular. I'm going to close this issue since it's really not actionable, but thanks for filing it. :)

**Comment by manikantag** [comment]
I see your point. 

But, even we couldn't cover end-to-end server side rendering (first rendering at server side for all routes), my suggestion is also about supporting server-side rendered main home/index page. 

Ex: When user visits, http://angular.io, server will generate the complete homepage markup. Once index page is loaded, from then on regular SPA flow continues. If user visits directly any other route, let the normal route resolution after complete app is loaded. 

This particular use case will also makes SEO friendly. Yeah, only homepage, where generally all other links and main/new information will be first published. Though Google started indexing JS apps, I m not sure about other search engines (but, I m little to not concerned about this). As long as Google sees my page without any issue, I m happy with that.

I've not gone through the New Router source yet, but to my guess, it'll be trivial to add support for this. How about something like this?

    // a new 'index()' method proposal
    $routeProvider.index('$root', { // I couldn't come up with better name for $path without any # or any route params - just the base href (or the domain)
        
        cache: true, // should router cache the server-rendered markup and re-use on next time user visits index route?

        redirectTo: '/' // redirect to this route when above 'cache' is set to false
    }) 
        
With one to two event hooks, cached server-rendered markup can be kept in sync.

Currently I m achieving, first by using server rendering the initial index page (using JSP), and have another template which is almost identical to the contents for JSP page for next time route change to index page (ex: / --> /#/contact --> /).

Please let me know your thoughts.
