### ISSUE TITLE
router.navigation

### ISSUE THREAD

**Issue by kamrenz** [angular/router#175]
It seems there is a possibility for us to tie into $router.navigation to show a spinner when the router is in transition. There is an example of this shown in animation... but doesn't work https://github.com/angular/router/blob/master/examples/angular-1/animation/index.html 

When debugging the source it seems like the startNavigation() function within the navigate() is never called. How can we actually tie into this? I have tried setting a $watch in the app controller on $router.navigating. It will trigger when it becomes true in the router's router.navigate() method. However, the $watch isn't triggered again when $router.navigating is assigned to false in the router's finishNavigating method.

**Comment by mick26** [comment]
$router.navigating does not change to true (i.e. is stays false even during route changes).

**Comment by btford** [comment]
This was addressed in 7d56e3de0fa005cfae5343bd5bbe0744d42add50, but hasn't yet been well-documented.

The behavior also is not well-defined for child routers.
