### ISSUE TITLE
ng-link should work with any route

### ISSUE THREAD

**Issue by timkindberg** [angular/router#181]
The ng-link directive works great if you have a route like `{ path: '/foo', component: 'home' }`. 

But, here are some instances where it falls apart.

**Multiple Paths Sharing Same Component** 
How would I use ng-link to get to the first route? the second route?
```js
{ path: '/a', component: 'a' },
{ path: '/b', component: 'a' }
```

**Sibling Components**
How would I use ng-link to get to this route?
```js
{ path: '/c', component: { primary: 'a', secondary: 'b' } }
```

**Proposed Solution 1**
The only thing I can think of to solve this is to give the route a name. The name would be used in the ng-link.
```js
{ name: 'a', path: '/a', component: 'a' },
{ name: 'b', path: '/b', component: 'a' },
{ name: 'c', path: '/c', component: { primary: 'a', secondary: 'b' } }
```
```html
<a ng-link="a">Go to A</a>
<a ng-link="b">Go to B</a>
<a ng-link="c">Go to C</a>
```
Couple issues with this is now ng-link would have to determine if its supposed to map to a route name or a component name (if there are duplicates, which wins out?)

**Proposed Solution 2**
Use a `link` config property instead of `name` and only allow ng-link to navigate by this property and **not** by component name.
```js
{ link: 'a', path: '/a', component: 'a' },
{ link: 'b', path: '/b', component: 'a' },
{ link: 'c', path: '/c', component: { primary: 'a', secondary: 'b' } }
```
```html
<a ng-link="a">Go to A</a>
<a ng-link="b">Go to B</a>
<a ng-link="c">Go to C</a>
```
Now the first link knows for sure that it's going to the route where `link` is `'a'`.

**Comment by jvandemo** [comment]
I think this was solved by adding the `as` property as discussed in #118.

**Comment by timkindberg** [comment]
oh yep you are right. duplicate.
