### ISSUE TITLE
'Could not instantiate controller' suppresses actual error message

### ISSUE THREAD

**Issue by wulfsberg** [angular/router#191]
The pipelineFactory function in router-directive.es5.js has a
`catch (e) {
    console.warn && console.warn('Could not instantiate controller', controllerName);
...
`
It would be nice to have the exception in the console log.

(Can't wait to get this router rolled into the main Angular release, by the way. It is *so* much nicer to work with).

**Comment by wulfsberg** [comment]
Ok, seems we stumbled across that one pretty much at the same time: Closely related to #190

**Comment by btford** [comment]
Definitely something worth fixing.

Yeah, going to close this in favor of #190. Let's continue discussion over there.
