### ISSUE TITLE
anchorLinkDirective applies to all mouse buttons

### ISSUE THREAD

**Issue by xwipeoutx** [angular/router#197]
I have a simple tag `<a ng-link="default()">`Foo</a>` and want left clicks to be handled by the router, and middle clicks to open the URL in a new tab.

Looks like the anchorLinkDirective is being fired for all buttons, causing the routing to take over and `event.preventDefault()` to be called instead.

Update: A simple way to repro is to middle-click one of the phone titles on the phone list page at
http://localhost:8000/examples/angular-1/phone-kitten/#/phones

**Comment by btford** [comment]
:+1: I'll look into it. Thanks!

**Comment by btford** [comment]
Same as #206, which is now fixed in master.

**Comment by xwipeoutx** [comment]
This isn't the same as #206 - this is about mouse button handling, the other is about a missing href value of the href attribute...
