### ISSUE TITLE
feat(helpers): create helpers module

### ISSUE THREAD

**Issue by jvandemo** [angular/router#211]
Currently helper functions like `dashCase()`, `'copy()`, `notMatched()`, `forEach()`, etc are defined in individual modules.

### Downside

- the helper functions cannot be unit tested directly
- the helper functions must be redefined in unit tests that require them (e.g. `dashCase()` is redefined [here](https://github.com/angular/router/blob/master/test/router-viewport.es5.spec.js#L607)), making it hard to maintain them

### Proposal

I would suggest bundling all helper functions in a helpers module and write unit tests for them.

The module could be called `helpers` so you can easily import required helpers in code and unit tests:

```javascript
import {helpers} from '../src/helpers';
```

### Plan

@btford &mdash; if you agree with the proposal, I am willing to invest the time to implement this and create a PR for it. Just wanted to check with you before I go ahead and implement it.

Feel free to let me know if you want to go ahead with this.

**Comment by btford** [comment]
Sounds good to me. Thanks @jvandemo!

**Comment by jvandemo** [comment]
@btford &mdash; Thanks for the confirmation, I will make it happen.

I will also reference and close this issue when the PR has been created to keep things tidy.

**Comment by jvandemo** [comment]
PR #212 has been created. Proposal can be closed.
