### ISSUE TITLE
Where to place services with new router?

### ISSUE THREAD

**Issue by Urbanviking** [angular/router#214]
I'm currently using ui-router and I would like to move to newrouter, but when I'm looking at the examples it seems as services are placed outside the component structure and a component only includes one  template and one controller.

See attached screen shot on how I've structured the app with ui-router.

Please advice/comment on best practice for placing services with newrouter.

Thank you in advanced!

![screen shot 2015-03-27 at 6 50 39 pm](https://cloud.githubusercontent.com/assets/5660611/6878301/39173710-d4b2-11e4-95bf-b7761ffe851c.png)

**Comment by nicksloan** [comment]
I encountered this myself with a new router project a few weeks ago. My instinct (as I've seen recommended elsewhere) was also to include services with their respective components. My last application was based on the older, out of fashion, approach to project layout that involved separating things by framework function (directives, controllers, services).

Obviously that approach doesn't work well for larger applications, but there is one attractive quality to it: shared services don't seem out of place.

I have found that there are lots of cases where I want to write a service that will be used by multiple controllers on different routes. As such, including the service in the component does indeed seem inappropriate.

The way I am building my application, I have a very strict separation of concerns: controllers are exclusively for moving data between the interface and my services. All of the business logic happens in my services. As such, I've had success with namespacing my services in a separate module (with submodules that group related services as necessary.

As far as directory layout, I keep that services module in it's own directory (as a submodule of my main application module), and then use subdirectories for the functionally related service submodules.

This has worked well for me, but I'd love to hear other ideas. I'd love to see some consensus develop around this like it has in previous Angular iterations.

**Comment by Urbanviking** [comment]
I think that I am going with encapsulation of controller, template and styling (CSS/SCSS) in own folder. It will be well prepared for the introduction of web components. The services will be placed in a shared folder for all services and later divided to sub-folders, if needed.

**Comment by nfantone** [comment]
Isn't this going somewhat against the [Angular Best Practice for App Structure](https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es) doc?
Or has that become obsolete by now? There is it clearly recommended to treat services and directives as components.

**Comment by Urbanviking** [comment]
I assume that Angular App Structure guidelines will be updated as Angular is moving towards 2.0. As services can be shared across multiple components, they should be placed in own folder. A component is defined as a script (controller) and a mark-up (template). This is true for both Angular components and Angular directives. I have included styling (CSS) with each component to ensure encapsulation. This is how Web Components are developed. Style consistency is kept by follow a style book.

**Comment by nfantone** [comment]
While that may be true, I'm still struggling to find it coherent on an Angular 1.x context.

> I assume that Angular App Structure guidelines will be updated as Angular is moving towards 2.0.

Seems unlikely, given that it hasn't been updated in a long while. Maybe a new standard proposal is on the making.

> As services can be shared across multiple components, they should be placed in own folder.

Yes, I agree. Typically within their own module, also. That is covered in the App Structure.

> A component is defined as a script (controller) and a mark-up (template). This is true for both Angular components and Angular directives.

But, generally speaking, it is *not* for services, filters, factories and providers. Also, directives do not need to strictly define a controller. Am I to understand from this that, with this new router, I could conceptually define a route to a directive? Sounds to me like the definition of _component_ has changed from that Google Doc.

With [angular/router](https://github.com/angular/router), what it's called to be a _subsection_ in the doc has now become a _component_. And what was called a _component_ (basically shared services and directives) should **not** be inside a `components` folder anymore. Am I right here?

> I have included styling (CSS) with each component to ensure encapsulation.

And, as per the style doc, you should also include all other assets (fonts, images, etc.).

**Comment by Urbanviking** [comment]
Service is not a component in neither Angular 2.0 nor Web Component definitions. I have folder named services. Service includes services, factories, providers. You shall see component as a widget. I keep images, videos separated from my code.

**Comment by nfantone** [comment]
Yes, I got your point. My angle is that while this may seem logic in an Angular 2.0/Web component world it doesn't quite fit in an Angular 1.x context. Specially if you take into account the aforementioned doc. 

I would like to a see an actual app scaffolding using this router.

**Comment by Urbanviking** [comment]
The attached picture above shows an actual app with ui-router and Angular 1.3. I also built a test app with Angular 1.4 router + Angular Material and another with Angular 1.4 router + Polymer to see what would be best approach moving forward. It is why I raised the question to hear others comment. Now, I have decided to follow the "web-component" approach.

**Comment by breandr** [comment]
Please reopen this as I'd like to see an official word on it. I'm in the same boat as you: services should be defined outside of components so they can be used by multiple components. However, this is to the detriment of transportability ie. you can't just grab a folder from one project/repository and add it to a project - you will also need to inspect the source to see which services are required and grab those as well.

@btford has there been any discussion on this?

**Comment by nfantone** [comment]
Yes. +1 to that.
