### ISSUE TITLE
Progress Document 

### ISSUE THREAD

**Issue by tomcon** [angular/router#226]
Hi Brian,
No doubt you've got a whole heap on the go but it looks like it should be removed from the main github page - I look at it regularly and it's not being updated/used.
(also the link "The tasks I'm working on this week are in the v0.4.1 milestone on GitHub" is broken)
Kind regards
Tom

**Comment by dcunited08** [comment]
Will the yet-to-be-named router be part of the RC0 release expected for this week?

**Comment by btford** [comment]
See https://github.com/angular/router/issues/234#issuecomment-89532206
