### ISSUE TITLE
ng-link does not working when route resolves more than one component [router.es5.js]

### ISSUE THREAD

**Issue by bl4de** [angular/router#227]
Hi,

I've got some issue when trying to use ng-link directive (I am using router.es5.js).
This is similar to https://github.com/angular/router/issues/118 , but I don't know how it should be used in ES5 version.

This is my example $router routes config:

```javascript
$router.config([
        {
            path: "/",
            redirectTo: "/home"
        },
        {
            path: "/home",
            component: {
                navigation: "navigation",
                main: "home",
                footer: "footer"
            }
        },
        {
            path: "/profile",
            component: {
                navigation: "navigation",
                main: "profile",
                footer: "footer"
            }
        },
        {
            path: "/about",
            component: {
                navigation: "navigation",
                main: "about",
                footer: "footer"
            }
        }
    ]);
```

and this is HTML uses it (it's separate component 'navigation' with navigation.html template):

```HTML
<div>{{navigation.title}}</div>
<div>
    <ul style="list-style: none;">
        <li style="display: inline; margin: 0 10px; text-decoration: underline;">
            <a ng-link="home">Home page</a>
        </li>
        <li style="display: inline; margin: 0 10px; text-decoration: underline;">
            <a ng-link="about">About us</a>
        </li>
    </ul>
</div>
```

Main HTML:

```HTML
<body ng-controller="MainController">
<header ng-viewport="navigation"></header>
<div ng-viewport="main"></div>
<footer ng-viewport="footer"></footer>
```
Unfortunately both links don't work and I'm not sure if I'm doing something wrong (probably) or maybe there's some inconsistency between ES5 and AtScript implementation of this particular usage.

Does every component's controller create its own scope and attributes for ng-link in navigation are not visible in MainController, where $router.config() is implemented?

The rest of application works properly (components are rendering, no errors in console, but also no reaction of <a> elements in navigation.html (above) after clicking.

**Comment by bunkered** [comment]
This is solved by using the `as` component. Take a look here: https://github.com/angular/router/issues/118

**Comment by rohanrehman** [comment]
@bl4de here is the implementation

    <a ng-link="channels">link:channels</a>

for the route
 ```javascript
{path: "/about",
            component: {
                navigation: "navigation",
                main: "about",
                footer: "footer"
            }, as:'about'
}
```

**Comment by bl4de** [comment]
@rohanrehman Works perfectly, thanks :)
