### ISSUE TITLE
[question] Rationale behind $router.navigate

### ISSUE THREAD

**Issue by cexbrayat** [angular/router#239]
I was wondering what the reasons are behind using a URL parameter in `$router.navigate` instead of a component name ?

To replace `$location.path('/register')`, I would have expect to write (maybe wrongly) : 

```
$router.navigate('register');
```

instead of 

```
$router.navigate('/register');
```

I was a bit surprised, as `ng-link` is working with component names.

To avoid remembering the URL, it's possible to do : 

```
var url = $router.generate('register');
$router.navigate(url);
```

But that feels overkill... Am I missing something ? Or what are the reasons to use a url instead of a component name ?

**Comment by corbanbrook** [comment]
I agree, also using the component names would make it work like $state.go in ui-router as well.

**Comment by notrab** [comment]
👍

**Comment by Simon-Li** [comment]
+1 expect answers as well.

**Comment by ocombes-oss** [comment]
+1
