### ISSUE TITLE
Scope Leak in custom directives

### ISSUE THREAD

**Issue by KSanthanam** [angular/router#241]
A custom directive for password match works in 1.x with old routers, but not with ngNewRouter. Please test this code http://plnkr.co/edit/FipgiTUaaymm5Mk6HIfn?p=preview inside a component with ngNewRouter & 1.4. I consistently get undefined value for scope.otherModelValue. Not only that I don't get access to any property of the component I made for ngNewRouter.

Please advice is this a bug? or am I missing something?.  

Update: I am extremely sorry. There is NO ISSUE here. I literally wasted 15 hrs due to a typo. I had typo on the attribute value ('singup' instead of 'signup'). Please ignore this issue. My apologies if anyone worked on this issue meanwhile

**Comment by KSanthanam** [comment]
Update: I am extremely sorry. There is NO ISSUE here. I literally wasted 15 hrs due to a typo. I had typo on the attribute value ('singup' instead of 'signup'). Please ignore this issue. My apologies if anyone worked on this issue meanwhile

**Comment by btford** [comment]
It's okay. :)
