### ISSUE TITLE
Pipeline API Issue/Question

### ISSUE THREAD

**Issue by pmorris3** [angular/router#249]
After reading the unit tests for the pipeline, I was able to actually use the pipeline API.  At least I was able to do so in a cursory sort of way.  However, as the API is a config function for the pipeline provider, very few things can actually be injected into the custom routing steps being defined.  All we get to call are providers and constants.

There are some pretty strong implications with regards to how the API can actually be consumed.  It means, that any custom steps we wish to write, can not include injectables which don't meet those criteria.  Unless there is something I am missing.  No custom services in pipeline steps, no native angular services in pipeline steps, etc.  

Given the use cases laid out in talks at one of the ng-conf's regarding the pipeline, I would have thought that the custom steps would need to be able to support the injection additional services.  Having said that, I do understand how the config function works in angular.  There is a good reason for wanting the routing pipeline configured before the routing service is instantiated, given angular 1.x's architecture.

Is this the intended end state?  Am I missing something, or should we only be able to access the internals of the router + native javascript inside of whatever we write as a function and turn into an injectable with provide?

**Comment by gautelo** [comment]
I'm not sure, but I think you can actually get access to most things. Consider the `runCanActivateHookStepFactory` function that implements the `$runCanActivateHookStep`. In short the trick is not to want to create the step inside the config block. In the config block you simply reference an injectable by name and the pipeline will use the `$injector` to find it.

```javascript
  .config(['$pipelineProvider', function($pipelineProvider) {
    // Add another step to the routing pipeline!
    var steps = $pipelineProvider.steps;
    steps.push('myNamedStep');
    $pipelineProvider.config(steps);
  }]);
```

You can then implement `myNamedStep` as whatever kind of service you like and inject whatever you need. If you need to access application state, the `instruction` holds the controller where that state resides. You could access it directly or do what the `runCanActivateHookStepFactory` does and call a method; `canActivate` on it through the `$injector` giving you great flexibility for different controllers to do different things at your custom step.

Doing this sort of thing should be simpler imo, but I think that's a matter of building some better api abstractions on top of what's there.

**Comment by pmorris3** [comment]
Sorry it took me awhile respond.  I was deeply buried with work when I saw your initial response come through and I couldn't break away to respond because of what I was working on.  As it happens, what you suggest is exactly what I wanted to do, but I somehow convinced myself that I couldn't.  I think I must have left some artifact in my test code which precluded it from working.  Maybe I was feeling the need to inject the service when it wasn't necessary.  It was 22 days ago when I was thinking about this, so my memory is a little hazy.

I will make a point of spending some time on it this weekend, to answer the question and post back, so I can report.  Maybe this thing can be closed out.  If so, I might even attempt a write up of how one can actually use the pipeline API at some point.  Thanks for the response!

**Comment by gautelo** [comment]
No worries. Looking forward to your findings.

**Comment by pmorris3** [comment]
I had some time to work with the router this weekend, and here is what I have come up with so far.  First, adding a step to the router is pretty simple.  In my initial tests, I was actually just passing a replacement array of steps into the $pipelineProvider.config call.  I have changed that for the moment, and am now just splicing my step into the existing array.  Actually getting a value into the config, was working.  The issues I had were tied up in what to pass into the config step.  Here is what I am using at the moment in my tests to initialize my pipeline.  It adds a step called 'fooService' to in between the '$initLocalsStep', and '$initControllersStep', steps.

```
(function() {
    'use strict';
    angular
        .module('testApp';)
        .config(pipelineConfig);

    pipelineConfig.$inject = ['$pipelineProvider'];
    /* ngInject */
    function pipelineConfig($pipelineProvider) {
        $pipelineProvider.steps.splice(2,0,'fooService');
        $pipelineProvider.config($pipelineProvider.steps);
    }
}());
```

The actual issues I was having with my initial test, involved the creation of the function which has to be associated with the injectable 'fooService'.  It has to be a function, as that is what the router expects when it tries to execute the routing step.  You can't use a service or factory which is written with the revealing module pattern, at least not directly.  In general, you can use a value, service, factory, or provider which is configured to return a function.  However, you can't really inject things into a value.  So that is something to keep in mind.  Here is an example.

```
(function() {
    'use strict';
    angular
        .module('testApp')
        .value('injectionTest','foo');

    angular
        .module('testApp')
        .factory('fooService',fooService);

    fooService.$inject=['injectionTest'];
    /*ngInject*/
    function fooService(injectionTest) {
        return function routeStep(instruction) {
            return instruction.router.traverseInstruction(instruction, function (instruction) {
                return instruction.locals.custom = addValue(injectionTest);
            });
        };

        // A pointless function.  Just to show some FP using the injected value.
        function addValue(injectionTest) {
            var tmp = [];
            tmp.push(injectionTest, 'bar');
            return tmp;
        }
    }
}());
```

This will result in an injectable called custom being created and accessible to the controller, when the controller is instantiated.  It will contain an array which has the value ['foo', 'bar'].  This is sort of pointless code, except that it serves as a proof of that you can expose create a function which you expose via a factory/service/provider, and use dependency injection with said provider mechanism.

I don't think I would opt to write something using the revealing module pattern and mix this route step into another module.  I would rather just inject the capabilities needed into the route step I am writing and have better separation of concerns.  Having said that, I did manage to figure out a way to make it work.  You can't use revealing module pattern factories directly as routing steps, as the function you intend to use as the route step, has to be the actual injectable.  You can write a factory/service/provider which injects your revealing module pattern module and exposes a function which just returns a function referencing it.  Here is an example.

```
(function() {
    'use strict';
    angular
        .module('testApp')
        .service('fooService1',fooService);

    fooService.$inject=[];
    /*ngInject*/
    function fooService() {
        return { routeStep: routeStep };
        function routeStep(instruction) {
            return instruction.router.traverseInstruction(instruction, function (instruction) {
                return instruction.locals.custom = 'hello!'
            });
        }
    }

}());

(function() {
    'use strict';
    angular
        .module('testApp')
        .factory('fooService', fooService);

    fooService.$inject = ['fooService1'];
    /*ngInject*/
    function fooService(fooService1) {
            return function(instruction) { fooService1.routeStep(instruction); }
    }
}());
```

At some point, I want to some more exploring on what I can actually do with the instruction mechanism.  I have a few thoughts about things like redirecting the router or halting the load of a component based on a failed authorization check.  I haven't taken the time to dig into actually using it at this point.  Just how to actually get the service injected.  (I suspect, based on looking over the code and listening to some talks about it, that it should be very possible to do things like this, instead of extending every controller with a canActivate mechanism.)
