### ISSUE TITLE
Can we use html2js for component's html?

### ISSUE THREAD

**Issue by heidi-de** [angular/router#250]
I am currently using html2js to convert HTML views into angular's $templateCache in order to save on HTTP requests. Is it possible to configure this behaviour for router components?

**Comment by ulrikaugustsson** [comment]
Should be possible, just have to tell html2js the correct path and it should work automatically, it uses the same mechanism to load the templates as any other template.

**Comment by heidi-de** [comment]
The router expects to find the html views of components on the path configured using $componentLoaderProvider, so to clarify my question will the router automatically pick them up from the $templateCache?

**Comment by ulrikaugustsson** [comment]
As I said, it uses the same mechanism as any other template and should work out of the box. the $componentLoaderProvider is just supplying the path. At least that is what I found when I followed the code in some debug session.

**Comment by heidi-de** [comment]
ok, great :-) Thanks!
