### ISSUE TITLE
sibbling-routes example throws error

### ISSUE THREAD

**Issue by KSanthanam** [angular/router#258]
Has anyone successfully implemented this example. 

I get the following error. The component directory does not have .js file. So I added the Controllers. Still it throws error. 

**components/posts/posts.js**

angular.module('myApp.posts', [])
    .controller('PostsController',PostsController);

function PostsController() {
	var self = this;
}

**components/users/users.js**

angular.module('myApp.users', [])
    .controller('UsersController',UsersController);

function UsersController() {
	var self = this;
}

Could not instantiate controller UsersController   router.es5.js:384 
Could not instantiate controller PostsController   router.es5.js:384 

Note: using 
https://code.angularjs.org/1.4.0-rc.0/angular.js

**Comment by KSanthanam** [comment]
The example needs to be modified to include the injection of myApp.users and myApp.posts. Closing it now.

**Comment by tommck** [comment]
The example also needs to have its spelling fixed.  It's "sibling", not "sibbling" :)
