### ISSUE TITLE
Ability to provide already loaded controller and template

### ISSUE THREAD

**Issue by Antontelesh** [angular/router#268]
New router seams pretty good, but I have a question.

Usually in production we don't have separate files for controller and template — all assets are stored in one minified bundle, generated by Browserify, Webpack or others. But the router assumes that there is a folder named `components` which contains separate files for each component. Configuring file naming in `$componentLoaderProvider` does not resolve the issue as there is no files to load at all.

Please provide ability to use the new router with inline template and controller code.

**Comment by nikaspran** [comment]
Could this be solved by populating `$templateCache`?

**Comment by Antontelesh** [comment]
Maybe yes, but it is a workaround. And it doesn'solve the problem with controller loading.

I think, minifying and concatenating statics is too common practice to neglect it. Workarounds there should not be satisfactory.

**Comment by nikaspran** [comment]
`$componentLoaderProvider.componentToCtrl()` doesn't actually load files at all, so I don't see how controller loading is related to the router at all. Basically, as long as they're registered, it's going to retrieve them (it's using the standard $controller service).

As far as `$templateCache`, it doesn't seem like a hack to me at all. In fact, in many toolchains if the files are minified, it's doing this already (putting things in `$templateCache`), see [grunt-angular-templates](https://www.npmjs.com/package/grunt-angular-templates).

**Comment by Antontelesh** [comment]
Understood. You may close if you wish.

**Comment by SanderElias** [comment]
@Antontelesh, you are the issue's owner. You can close it yourself. (or wait for Brian or another maintainer to close it, but let them concentrate on things that really matter right?)
