### ISSUE TITLE
Unit test example?

### ISSUE THREAD

**Issue by dereklin** [angular/router#278]
Hi, 

Before we used the new router, we can write tests like this:

  beforeEach(inject(function(_$rootScope_,_$compile_,_$controller_) {
	  
	  scope = _$rootScope_.$new();
      compile = _$compile_;
      controller = _$controller_;
	  MyCtrl = controller('MyController', {
	    	$scope: scope
	  });
	  
  }));
  

It crashes after using the new router.  Do I need to change this?  I tried removing everything inside the function block, but it still fails.

Is there some example of unit tests with the new router implemented?

**Comment by btford** [comment]
Can you please provide a runnable reproduction via [jsbin](http://jsbin.com/), [plnkr.co](http://plnkr.co), or [jsfiddle](http://jsfiddle.net/)?

If not, can you provide a stack trace?

This saves me a lot of time. Thanks!

**Comment by dereklin** [comment]
@btford It turned out that I misspelled my component when mocking:  Instead of module('myApp.myComponent'); I did module('myApp.mycomponent');  Your response indicated that the normal unit tests should continue to run.  Thank you for pointing me to the right direction!

**Comment by btford** [comment]
Hah, you're welcome. :)
