### ISSUE TITLE
Define components and component in the same $routeConfig

### ISSUE THREAD

**Issue by QuinntyneBrown** [angular/router#281]
Could you create an example where you are defining a component and components in the the same $routeConfig.

Your examples demonstrate a single outlet app or a master detail style app. There will be cases where you need to develop an app with a single outlet as well as a master detail (multiple named outlets).

**Comment by btford** [comment]
Not sure I understand.

`component: 'foo'` aliases to `components: { default: 'foo' } }`. You should not be using both `component` and `components` in the same config; you should always use `components` in cases where you have siblings.

**Comment by QuinntyneBrown** [comment]
Thanks for the response, I did not know about "components: { default: 'foo' } }"  I think a great example would be to implement a splash (about) page and then a master detail page in the same SPA.
