### ISSUE TITLE
Angular 1.3 - How to use $scope.$on inside controller because $scope is no longer work

### ISSUE THREAD

**Issue by lovedota** [angular/router#284]
Hi guys.
Sorry I am new to **angular-new-router**. How can I upgrade from **angular-route** to **angular-router**
I changed using **$scope** to **this**, but some event subscribing like ```$scope.$on`` How can I replace them. Thanks !

**Comment by jameswyse** [comment]
I'm using the `activate` method (add it to your controller's prototype) to access `$scope` at the moment. Not sure if it's ideal, or even intended, but it works!

From memory, something like this should work:

```javascript
class YourController {
  constructor (UserModel) {
    this.UserModel = UserModel;
  }
  
  activate ($scope) {
    $scope.$on('userUpdated', (e, user) => {
      $scope.user = new this.UserModel(user);
    });
  }
}
```

**Comment by btford** [comment]
This has since been fixed in master; you can now ask for $scope in controller constructors.
