### ISSUE TITLE
Include bower.json file

### ISSUE THREAD

**Issue by armandoborge** [angular/router#289]
Include a bower.json file could be helpful, for example Wiredep (https://github.com/taptapship/wiredep) along with Gulp/Grunt  uses the information in the bower.json file in order to injecting dependencies between placeholders in your source code, this is a common task for Yeoman's generators, also could be helpful for other tools which conform to the Bower specification.

**Comment by PascalPrecht** [comment]
@armandoborge you can always just point to a GitHub endpoint (`angular/router`) when using Bower.

Other than that I think it's better to get the information from `package.json` since npm is officially supported as a package manager. Not really sure if bower will be supported.

**Comment by armandoborge** [comment]
Not sure neither, but adding the bower.json file won't be too much work and will help a lot people working with Bower and Yeoman... is ok if I make a new PR for include the file?

**Comment by Nevraeka** [comment]
:+1: @PascalPrecht Polymer has had some issues with Bower as well. I do see the point that @armandoborge has that it is easy to implement and speaks to a large amount of users. I guess my questions to the team are 1)  will maintaining another config file be more complex then needed? 2) Does a bower config break coding style and patterns commonly seen in Angular? In other words, does this defy the repository standards for Angular repos?

**Comment by malcomm** [comment]
Any update on this? Without the main being defined in bower.json, basically makes it very difficult to use via bower.

> Re: 2) Does a bower config break coding style and patterns commonly seen in Angular? In other words, does this defy the repository standards for Angular repos?

Looking at the core Angular code:

https://github.com/angular/bower-angular

Both bower.json and package.json are used. From what I've seen this is pretty much the standard. I'm not a huge fan of having to maintain both and it would be nice to keep to DRY, but at this point, this is where we are at.

**Comment by armandoborge** [comment]
Hi @malcomm 

Nothing defined so far... However you can use it with bower easily, just point to a GitHub endpoint as @PascalPrecht is suggesting or update your bower.json file and include an override:

```javascript
  "overrides": {
    "angular-new-router": {
      "main": "dist/router.es5.js"
    }
  },
 ```
See: https://github.com/taptapship/wiredep#bower-overrides

**Comment by malcomm** [comment]
Hi @armandoborge,

Cheers for the quick reply, the overrides approach works great. Saved me time looking for this solution, appreciated.

**Comment by armandoborge** [comment]
Glad to help @malcomm
