### ISSUE TITLE
dist vs. src

### ISSUE THREAD

**Issue by manfredsteyer** [angular/router#290]
Hi,

I've just noticed, that the dist and the src-folders seem to be out of sync. The last update to the dist-folder has been about 20+ days ago, while the last update to the src-folder has happend about 3 days ago.

Is there a reason for that or is this just by accident?

Wishes,
Manfred

**Comment by PascalPrecht** [comment]
It's not an accident. The dist folder gets updated on every release that gets cut, where as the src folder is updated constantly as changes are introduced.

**Comment by manfredsteyer** [comment]
I see. Thx for your quick reply.
