### ISSUE TITLE
Karma bootstrap error

### ISSUE THREAD

**Issue by Simon-Li** [angular/router#296]
Here is the log running up Karma, but with errors. Just curious how this file 'node_modules/rtts-assert/dist/amd/assert.js' can be found to fit here, otherwise, Karma returns errors. Any clues? Thanks

[root@vm router]# karma start karma.conf.js
WARN [karma]: Port 9876 in use
INFO [karma]: Karma v0.12.31 server started at http://localhost:9877/
INFO [launcher]: Starting browser Chrome
ERROR [launcher]: No binary for Chrome browser on your platform.
  Please, set "CHROME_BIN" env variable.
WARN [watcher]: Pattern "/opt/playG/router/node_modules/rtts-assert/dist/amd/assert.js" does not match any file.

**Comment by nikaspran** [comment]
The real error is here, I would think:

```
INFO [launcher]: Starting browser Chrome
ERROR [launcher]: No binary for Chrome browser on your platform.
Please, set "CHROME_BIN" env variable.
```

**Comment by Simon-Li** [comment]
@nikaspran I removed the browsers options entirely in the karma.conf.js, but the error still exists as below. I think it's because of missing this file 'assert.js', any clues of how to get this file configured properly. I installed the 'rtts-assert' module via the npm install, but there is no such folder and file as this "/dist/amd/assert.js", any idea? thanks!

[root@vm angular-router]# karma start karma.conf.js
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
WARN [watcher]: Pattern "/opt/playG/angular-router/node_modules/rtts-assert/dist/amd/assert.js" does not match any file.

**Comment by btford** [comment]
Did you npm install?

**Comment by Simon-Li** [comment]
Ye, 'npm install rtts-assert'

**Comment by Simon-Li** [comment]
Is an issue related to 'npm install rtts-assert'? so as the file "assert.js" can not be installed properly...

**Comment by Simon-Li** [comment]
See https://github.com/angular/router/blob/master/CONTRIBUTING.md#setup
