### ISSUE TITLE
[Question] How to use new Router with Typescript and Angular2

### ISSUE THREAD

**Issue by KhaosTheory1012** [angular/router#302]
see title.
http://codepen.io/jvandemo/pen/gbKNox?editors=101
Only found this example can anyone tell me how to change things up to make it work for typescript?

**Comment by Simon-Li** [comment]
as mentioned a few days ago, i guess @btford will have a example soon for this, right?

**Comment by johnjelinek** [comment]
:+1:

**Comment by armorik83** [comment]
+1

**Comment by diliondani** [comment]
+2

**Comment by hannahhoward** [comment]
I think examples are coming but in the meantime you may want to checkout:

[configuration.md](https://github.com/angular/router/blob/master/docs/content/configuration.md)

and if you're comfortable reading source code:

[router in Angular 2 repo](https://github.com/angular/angular/tree/master/modules/angular2/src/router)

**Comment by johnjelinek** [comment]
I tried to import RouteConfig, but I guess it's not included in the current `angular2.dev.js` bundle. What's the recommended way of getting it into my project? Build angular2 from source?

**Comment by baio** [comment]
+1

**Comment by hannahhoward** [comment]
hey all, just one more thing, if you'd like to try using the router with Angular 2's syntax but can't get it to work in NG2, you can use my library A1AtScript which translates Angular 2 syntax including the router to Angular 1: [https://github.com/hannahhoward/a1atscript](https://github.com/hannahhoward/a1atscript) . There's also a starter project here: [https://github.com/hannahhoward/a1-starter](https://github.com/hannahhoward/a1-starter)

**Comment by KhaosTheory1012** [comment]
Okay I tried to figure out some stuff using the angular.io repo (router branch) for a guide but it is not working (using TS and ng2 .22 alpha)

import {Component, View, bootstrap} from 'angular2/angular2';
import {RouteConfig, Router, RouterOutlet, RouterLink, routerInjectables} from 'angular2/router';
import {HomeComp} from './components/home/home';
import {DetailComp} from './components/detail/detail';
@Component({
    selector: 'my-app'
})
@View({
    template: '< router-outlet>< /router-outlet>',
    directives: [RouterOutlet, RouterLink, HomeComp, DetailComp]
})
@RouteConfig([
    { path: '/', component: DetailComp },
    { path: '/detail', component: HomeComp }
])
class AppComp {}
bootstrap(AppComp, routerInjectables);

import {Component, View, bootstrap} from 'angular2/angular2';

@Component({
    selector: 'detail'
})
@View({
    template: 'Hello {{name}} This is DETAIL'
})
export class DetailComp {
    name:string;

    constructor() {
        this.name = 'Detail';
    }
}

bootstrap(DetailComp);

Home looking almost alike. And it just shows me the DetailComp (i can switch them out and its the other way around)

index.html:

<!doctype html>
< html lang="en">
< head>
    < meta charset="utf-8">
    < base href="http://localhost:8080/">
    < title>My app</title>

    < script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"> < /script>
    < script src="https://jspm.io/system@0.16.js"></script>

    < script src="https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js"></script>
    < script src="https://code.angularjs.org/2.0.0-alpha.22/router.dev.js"></script>

< /head>
< body ng-app="myApp" ng-controller="AppController as app">

< script>
    System.import('app');
< /script>

< label>Link 1:</label>< a ng-link="home()">Home</a>
< label>Link 2:</label>< a ng-link="detail()">Detail</a>

< my-app>< /my-app>

< /body>
< /html>

**Comment by johnjelinek** [comment]
I don't think you're supposed to use `ng-link`. I'm not sure what it's supposed to be.

**Comment by johnjelinek** [comment]
ya -- try `router-link`: https://github.com/angular/angular/blob/ecb068019bd218d2cc466a8cf1de47ed3b99c1d3/modules/angular2/test/router/outlet_spec.js#L141

**Comment by rolandjitsu** [comment]
@KhaosTheory1012 I have managed to successfully setup routing using alpha version `25`. You can see a working example [here](https://github.com/rolandjitsu/ng2-play). If you want to use TS, follow the docs guidelines how to set it up, but the rest should be the same setup.

**Comment by KhaosTheory1012** [comment]
@rolandjitsu Thanks but I already made it work with .23 alpha just forgot to update this issue
