### ISSUE TITLE
Can two different routes share the same controller and view (component)?

### ISSUE THREAD

**Issue by frodefi** [angular/router#321]
My use case: I have the same controller and view for two routes: Edit profile and view profile, but when I switch from view profile to edit profile via a link using `ng-link`, the view is not updated with new values that the controller changes for this new route. When clicking on the edit-route, it seems from my console-logs that the controller is run 2 times, first with the old route information once, and then again with the new route information (but view is not synchronized). See [this plnkr](http://plnkr.co/edit/7nhIwvhQmNNWsdpPHrhd?p=preview) (and compare the console-log with the view).

And when I try to add $scope to the controller to be able to do a $scope.apply I get the very cryptic error message: `Could not instantiate controller ProfileController   router.es5.js:384`

Is this at all possible?

**Comment by ivahaev** [comment]
You can use params in route.
My example:
```javascript
path: '/account/:mode/index.html', component: 'account'
```
In view:
```html
<a ng-link="account({mode: 'view'})">View account</a>
<a ng-link="account({mode: 'edit'})">Edit account</a>
```

And then in AccountController switch of $routeParams.mode

**Comment by ivahaev** [comment]
> And when I try to add $scope to the controller to be able to do a $scope.apply I get the very cryptic error message: Could not instantiate controller ProfileController router.es5.js:384

Because there is not `$scope` in Angular 2.0. But you can use $rootScope.

**Comment by heidi-de** [comment]
#313 seems to indicate that $scope is fixed in master, it is just not in the current release.

**Comment by frodefi** [comment]
@ivahaev, ok that partly solves it, except that forces a path style that I might now want.

For example, I would like to have the following paths related to an order:
See order: `/orders/:id``
Edit order: `/orders/:id/edit`
New order: `/orders/new`

See [this plnk] where I have attempted it, but it does not work, it looks like both parameters needs to be present.

Can the new router handle this case (if I want to use the same component for all 3 cases)?

**Comment by ivahaev** [comment]
@frodefi, I use such routes in this case:
View order: `/orders/:id/view`
Edit order: `/orders/:id/edit`
So, when you add an order, route will be `/orders/:id/edit`, where `id` is `new `

**Comment by frodefi** [comment]
@ivahaev, ok so you have found a workaround. Does not looks so nice for the "new" case, sine /orders/:id/new does not make sense.

But thank you for your tip! I am using it now :) I will close this issue and create a new one, specifically for my use case.
