### ISSUE TITLE
Using templateCache: Error: [$compile:tpload] Failed to load template: ./components/welcome/welcome.html (HTTP status: 404 Not Found)

### ISSUE THREAD

**Issue by dereklin** [angular/router#323]
I am trying out the hello example, but with templateCache...

And I am not sure if this question pertains to https://github.com/angular/router/issues/250

But I am getting Error: [$compile:tpload] Failed to load template: ./components/welcome/welcome.html (HTTP status: 404 Not Found)

What steps am I missing?:

And I have:

```
angular.module("example").run(["$templateCache", function($templateCache) {$templateCache.put("components/flickr/flickr.html","<section><h2>{{flickr.heading}}</h2><div class=\"row\"><div class=\"col-sm-6 col-md-3\" ng-repeat=\"row in flickr.images\"><a class=\"thumbnail\"><img style=\"width: 260px; height: 180px;\" ng-src=\"{{row.media.m}}\"></a></div></div></section>");
$templateCache.put("components/welcome/welcome.html","<section><h2>{{welcome.heading}}</h2></section>");
$templateCache.put("components/settings/settings.html","<section><h2>{{settings.heading}}</h2><div><div class=\"col-md-2\"><ul class=\"well nav nav-pills nav-stacked\"><li><a ng-link=\"flickr\">flickr</a></li><li><a ng-link=\"settings\">settings</a></li><li><a ng-link=\"welcome\">welcome</a></li></ul></div><div class=\"col-md-10\" style=\"padding: 0\"><ng-outlet></ng-outlet></div></div></section>");
```

**Comment by heidi-de** [comment]
You need to configure the pattern to use components/... instead of ./components/... using the componentLoaderProvider:
See here: https://angular.github.io/router/$componentLoaderProvider

**Comment by alexrada** [comment]
I fixed this using the following code. Someone could confirm and close the issue.

.config (['$componentLoaderProvider', '$httpProvider', function ($componentLoaderProvider, $httpProvider) {
  $componentLoaderProvider.setTemplateMapping(function (name) {
    var dashName = dashCase(name);
    return 'components/' + dashName + '/' + dashName + '.html';
  });
}])

**Comment by dereklin** [comment]
Thanks @alexrada and @heidi-de 

It's working.  My final code looks like:
```
.config (['$componentLoaderProvider', function ($componentLoaderProvider) {
	$componentLoaderProvider.setTemplateMapping(function (name) {
		var dashName = dashCase(name);
		return 'components/' + dashName + '/' + dashName + '.html';
	});
}])
```
And I have to use
```
<div ng-viewport></div>
```
instead of 
```
<ng-outlet></ng-outlet>
```
