### ISSUE TITLE
router-outlet does not contain the components in angular 2

### ISSUE THREAD

**Issue by rolandjitsu** [angular/router#325]
I just have a simple question, though I know that there isn't a stable version of angular 2, nor the router, but is the component supposed to be inserted inside the `<router-outlet></router-outlet>` or is it appended after it? The reason I ask is because I have it appended after as in the screenshot:

![screenshot 2015-05-19 09 32 26](https://cloud.githubusercontent.com/assets/1479737/7697668/04d9c8ec-fe0a-11e4-9bd2-1e27f5545451.png)

**Comment by ditoglez** [comment]
+1

**Comment by evanplaice** [comment]
+1 It's inserting the route contents correctly after `<route-config></route-config>` where it should be replacing the element.

**Comment by PascalPrecht** [comment]
This is by design as `router-outlet` just marks the place where the component should be inserted.

**Comment by rolandjitsu** [comment]
@PascalPrecht thanks for clarifying. But just a thought, an outlet is something where you put a thing in not near it :) That's why I found it confusing and asked.

**Comment by PascalPrecht** [comment]
Totally with you. In fact, `router-outlet` is going to be renamed to `router-viewport` again, which comes with the same semantic issue. However, maybe this should be considered an implementation detail

**Comment by rolandjitsu** [comment]
@PascalPrecht yeah, I think I am subscribed to that issue where the router name is being discussed on the angular 2 repo. I think that the most semantic name would be `router-anchor` (or `router-view-anchor`) if the implementation is left to add the views next to the components instead of inside.

**Comment by mattvot** [comment]
@rolandjitsu which issue is the one you are subscribed to? Thanks

**Comment by rolandjitsu** [comment]
@mattvot I cannot find the issue anymore, but I think it has been closed anyway and decided what will be the name.

**Comment by evanplaice** [comment]
@rolandjitsu Here it is angular/angular/issues/4679

**Comment by robertbrower** [comment]
I'd say that this is going to cause problems with layout if the view is inserted AFTER the element and not inside... makes it impossible to get a good layout.

**Comment by thomashilzendegen** [comment]
@robertbrower You could use the CSS "element follows element" selector:

`router-outlet + your-element`

**Comment by GaryChamberlain** [comment]
@thomashilzendegen The element is listed as an _undefined_ tag in the browser and this doesn't seem to work.

`router-outlet + undefined`

The contents of a component are inserted into the custom tag name, so why wouldn't the same happen with router-outlet?  I've seen "this is by design" in a bunch of places (many people asking about this) but no technical reason why it would be designed like this.  Strange.

It's confusing and makes it difficult to layout in CSS.  This _really_ should be addressed before Angular 2 is released!!  Maybe it is by design, but it looks like a bug.

**Comment by GaryChamberlain** [comment]
@mhevery @btford @IgorMinar Please consider reopening this and adding it to the release candidate.  It feels broken.  Developers are going to need to have some funky css to layout the router-outlet content which will make it difficult to fix later.

**Comment by GaryChamberlain** [comment]
![image](https://cloud.githubusercontent.com/assets/4453524/14056993/34dc9eb0-f2ca-11e5-9d47-752f37346ed7.png)

**Comment by GaryChamberlain** [comment]
I think I figured out my confusion.  It's two related things.

1] The name of the tag inserted after the router-outlet comes from the routed component's selector attribute.  I had followed the instructions on the Routing & Navigation page of the docs which states, "_It has no selector either. It doesn't need one._", and in fact the live example inserts an undefined tag.  The docs should communicate that the selector name will be used for the embedded tag name, and if it is omitted then _undefined_ will be used. @naomiblack 

2] It seems that sibling selectors don't work inside component style attributes.  I was thinking that it had to do with the name _undefined_. However, even after I set the selector attribute and had a name, it still didn't work.  When I move it to a styles.css file it works fine.

`router-outlet + your-element`

**Comment by Be-ngt-oH** [comment]
We've just discovered an alternative solution:

`:host router-outlet + *`

The trick is that only the host attribute is used and no additional attribute is added to the router-outlet and star selector. However I consider this to be a temporary workaround because I believe it should work as @GaryChamberlain wrote.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781521/6a5d5d36-b7be-11e6-9545-3e42130a77da.png)
![Uploading 图片.png…]()

**Comment by kal-a-1** [comment]
I wrapped the `<router-outlet>` in a div and it works for me

`<div><router-outlet></router-outlet></div>`

**Comment by robert-king** [comment]
this works, it also makes sense to wrap a div since the outlet could contain multiple top level elements:
```
<div style="height: 100%;
  display: grid;
  grid-template-rows: auto 1fr;">
  <app-nav></app-nav>
  <div>
    <router-outlet></router-outlet>
  </div>
</div>

```

**Comment by ShaggyDude** [comment]
Adding extra divs sux imho. Does the wildcard selector work? I think it would be ":host router-outlet > *" though. EDIT: The above is correct. The adjacent sibling selector "router-outlet + *" because of the strange non nested output.

**Comment by ShaggyDude** [comment]
From the parent component '::ng-deep router-outlet + *'
