### ISSUE TITLE
Wrong `main` in package.json

### ISSUE THREAD

**Issue by DrDanRyan** [angular/router#338]
I believe the `main` property in package.json should be "index.js"; it is currently set as "dist/router.es5.js". The contents of "index.js" are:
```javascript
require('./dist/router.es5');
module.exports = 'ngNewRouter';
```
The module.exports line allows me to do
```javascript
angular.module('myApp', [require('angular-new-router')])
```
with Webpack

**Comment by schmitch** [comment]
Yeah I have the same issue with browserify.

Currently it needs to be index.js

**Comment by jamestalmage** [comment]
Current fix is to do
```javascript
angular.module('myApp', [
  require('angular-new-router/index')
]);
```
or
```javascript
angular.module('myApp', [
  require('angular-new-router').name
]);
```
I would probably recommend the first option, since it will likely be backwards compatible once `package.json` is updated to point to the correct file.

**Comment by jamestalmage** [comment]
The fix is already merged (#136).
This should be closed once a new version is published to npm.

**Comment by schmitch** [comment]
Yeah I've seen that, thanks.

**Comment by krasevych** [comment]
Please, Can you add "main" into ".bower.json" ?
