### ISSUE TITLE
How would one use the $routeConfig within a Typescript controller?

### ISSUE THREAD

**Issue by maciossek** [angular/router#347]
This is how I solve it at the moment:
```
module app {
  'use strict';

  export class AppRoutes {
    static $inject = ['$router'];

    routes: Array<any> = [{ path: '/', component: 'app.home' }];

    constructor($router: any) {
      $router.config(this.routes);
    }
    
    canActivate() {
      return true;
    }
}
```

My question is how could I do it differently (without injecting the router service). 
A `static $routeConfig = [{...}]` property on the controller get read, but it does not show up as child router within the rootRouter.

**Comment by pascalbayer** [comment]
I'd the exact same issue using typescript, renaming the main application controller "AppController" works with `static $routeConfig = [{...}]`. As you can see in the code:
```
// line 1418 in router.es5.js
if (name === 'app') {
    name = '/';
}
```
Actually calling your controller "/Controller" has the same effect as name parameter passed will be "/" then.
