### ISSUE TITLE
set ng-link directive dynamically

### ISSUE THREAD

**Issue by maciossek** [angular/router#355]
`ng-link="app.toolassembly({ id: {{buttonOverviewCtrl.currentToolAssemblyId}} })"` is correctly rendered in html, but ng-link does not seem to be updated after currentToolAssemblyId changes. 

HTML: `ng-link="app.toolassembly({ id: 42 })"
Resulting URL when click:`/myapp/toolassembly/undefined"

**Comment by kenkouot** [comment]
I believe the correct syntax is:
```
ng-link="app.myRoute({ myId: myModel.value})"
```

**Comment by maciossek** [comment]
I am using the correct syntax though, but when I call $digest on the rootscope the link is still undefined
