### ISSUE TITLE
Programmatically navigation in new router

### ISSUE THREAD

**Issue by Toadskin** [angular/router#361]
What's the "official" programmatic equivalent of ng-link to execute from within your controller?  Whether with the basic router or the ui-router, and now with the new router, we rarely declare links directly in the markup.  More typically, we click something, do something, then programmatically navigate.

**Comment by rhllor** [comment]
same issue. 
Any solution?

**Comment by csgruenebe** [comment]
I also would like to know how this works.

**Comment by PascalPrecht** [comment]
It's `router.navigate()` or `router.navigateByUrl()` depending on what you have available to route to a component.

Also keep in mind that this repo here is on hold and that all the development is happening over at http://github.com/angular/angular.

**Comment by csgruenebe** [comment]
ok and thanks a lot :)
