### ISSUE TITLE
Extra div by using ng-outlet

### ISSUE THREAD

**Issue by Zizzamia** [angular/router#377]
In my page by using `ng-outlet`.
```html
<ng-outlet class="app"></ng-outlet>
```
I aspect something like, where `month-cmp` it's just my directive view.
```html
<ng-outlet class="app" month-cmp>
  <div class="tasks"><div>
</div>
```
Instead I have an extra `div` that will start  creating some possible css conflict.
```html
<ng-outlet class="app ng-scope" month-cmp>
  <div month-cmp>
    <div class="tasks"><div>
  </div>
</div>
```

**Comment by btford** [comment]
Track this issue here –> https://github.com/angular/angular/issues/5107

**Comment by vguede** [comment]
Duplicate of #5078
