### ISSUE TITLE
Odd routerLink behavior, must click to add href attribute...

### ISSUE THREAD

**Issue by tracker1** [angular/router#400]
When I navigate off of the first route to render, the resulting navigation area (Home and BF.Index are effectively the same template), the A elements in the DOM don't have any href attribute, and don't render as links.  Once I actually click on one of the two A elements, they then change to links.

This behavior is weird and unexpected.  Am I missing something?  (NOTE: using babel for es6/7 transpilation, not TypeScript)

[Screenshots Here](http://imgur.com/a/HC91p)

* Image 1 shows initial render.
* Image 2 shows after navigation to /bf
* Image 3 shows after clicking on A element

[Here's a clone](https://github.com/tracker1/angular2-webpack-es6/tree/master/client), with the minimum code for the issue.

I tried to replicate the issue on Plunkr, but wasn't able to replicate the issue, the plunkr version is typescript, couldn't find a babel/es6 version of angular I could use on plunkr...

working: https://plnkr.co/edit/GmEhw9

**Comment by PascalPrecht** [comment]
Hi @tracker1 can you please setup a plunk that demonstrates your issue. And please make sure that it's broken down to just what's needed to show the issue. Thanks!

**Comment by tracker1** [comment]
@PascalPrecht I'm not sure how I can simply demonstrate *just* the issue with plunk...  Beyond that, most paste type sites are blocked from my work location (large banking company).

I don't know how I can make it simpler than the components I pasted in the description.  Seriously, it's about as simple as it can get...  Just look at the template... there's nothing there, look at the screenshots I just added.

**Comment by tracker1** [comment]
@PascalPrecht here's my attempt to get it into a plunker, but the Angular2 router isn't loading... and I'm not sure what I need to add to make it actually work...

https://plnkr.co/edit/GmEhw9

**Comment by tracker1** [comment]
Updated the plnkr, and now getting `provide is not defined` from `angular2-polyfills.js` line 1243...

**Comment by tracker1** [comment]
It appears to be something to do with `babel-polyfill`  I converted the project to typescript to see if that fixed it.. but it wasn't until I removed the referenct for babel-polyfill that it started working.
