### ISSUE TITLE
Latest releases are not available via npm?

### ISSUE THREAD

**Issue by Chyngyz** [angular/router#403]
The latest one on npm is 0.2.0, can you update it?

**Comment by maciej-kolodziejczak** [comment]
For now, use npm install @angular/router

**Comment by ma-zal** [comment]
`npm install @angular/router` in 0.2.0 contains issue https://github.com/angular/angular/issues/4633. So it is not working correctly.

**Comment by marcalj** [comment]
It doesn't contains angular1 code in rc1 version.
