### ISSUE TITLE
Using router in ES6?

### ISSUE THREAD

**Issue by Chyngyz** [angular/router#408]
What's name of the router to import in es6, `angular-new-router`, `ngComponentRouter ` none is working?

**Comment by stnor** [comment]
If you're using the unofficial npm package,  **npm i ngcomponentrouter --save** you would **import 'ngcomponentrouter'**;

**Comment by dimitarrusev** [comment]
@Chyngyz Use the file's canonical path in your ([import statement](http://stackoverflow.com/questions/35839053/using-angular-new-router-with-es6/37632060#37632060)).

**Comment by Chyngyz** [comment]
@dimitarrusev Thanks a lot, closing the issue.
