### ISSUE TITLE
Production ready? Which version?

### ISSUE THREAD

**Issue by derek-adair** [angular/router#417]
I much prefer angular-new-router over the old way of doing things.  I'm in the alpha stages of a admin interface that will need to be maintained over a long period of time.  I made the mistake of doing a first pass w/ the npm version of angular router.  Things are working but there are several features not there that I would like.

Currently looking at this repositories tags, it looks like 0.5.3 was the last "release".  Which version would you all recommend using?

**Comment by thvd** [comment]
As described here https://docs.angularjs.org/api/ngComponentRouter you should use version `0.2.0`.

**Comment by derek-adair** [comment]
Ya, thats what i'm using now.  Dang, was really hoping to take advantage of newer version.  Particularly because nglink isn't setting an active state class, which seems to be in the newest version of router.
