### ISSUE TITLE
This project is deprecated... right?

### ISSUE THREAD

**Issue by derek-adair** [angular/router#421]
[Are the new angular 1.5.7 doc's accurate](https://docs.angularjs.org/guide/component-router)? this project is deprecated?

If so please make this abundantly clear.

**Comment by bedag-moo** [comment]
As far as I can tell from the git history, @petebacondarwin has reused this repository for a backport of angular2's component router, which is intended to replace the deprecated angular 1 component router previously hosted here, to whom most of this repository's issues and pull requests apply.

**Comment by petebacondarwin** [comment]
Yes, right now this whole repo is kaput.
I'll update the README.

**Comment by derek-adair** [comment]
Thank you... and BLAARGHALKJHRKLJHAFKJLHK!JH_!&#$^(_&^ dammit.
