### ISSUE TITLE
What I liked so much about durandalJS and wish for the new angularJS router

### ISSUE THREAD

**Issue by bastienJS** [angular/router#48]
This is a feature request for something I have used in durandalJS and which is not existing at all in the angular ui router 0.2.13 and I am really surprised how well the architecture from durandalJS was where people are praising the ui router 0.2.13...

Please give the API user function hooks like active , canActivate, etc... where the user can put the logic inside the "controller" and prevent leaving an url like "do you want to save?". Using the global '$stateChangeStart" hook is not funny. This leaves duplicate code and not encapsulated.

Also consider create a guardRoute function: 

http://stackoverflow.com/questions/17089694/how-to-handle-ignore-a-bad-route-with-durandal
 
Thanks!

**Comment by btford** [comment]
Thanks for the feedback! This is already implemented, so I'm going to close this.
