### ISSUE TITLE
Ability to activate a controller function 

### ISSUE THREAD

**Issue by niemyjski** [angular/router#53]
I just thought that this might be a nice to have and hopefully it gets feedback from others.. Lets use this GitHub issue as the scenario

So My route to view the issue is `issues/:id` and lets say that we also have the actions on an issue like close. We might want to link to these and run the action so we'd want an optional parameter like issues/:id/action.

Currently in UI-Router we'd have to create two routes so that issues/:id and issues/:id/:action both resolve. Then we have to check state params and call the right function.

It would be kind of sweet if I could link to issues/my_id/close and it would resolve with state: { id: 'my_id', action: 'close' } and it would instantiate my controller and then try to call a function called close() on my controller if it exists.

Thoughts?

**Comment by niemyjski** [comment]
I was thinking that maybe you define the route param as &action and if it's prefixed with & then try and call it as a function.

**Comment by niemyjski** [comment]
Having something like this would save us from having to do boiler plate code  like this commit: https://github.com/exceptionless/Exceptionless.UI/commit/c24a6f14411e224c05b31d42b0799d2b543a41b6

**Comment by btford** [comment]
I think this is an interesting idea, but I don't think it really needs to be a default behavior.

Right now, you could do it like this:
```js
class ActionClass {
  constructor(routeParams) {
    this.params = routeParams;
  }
  activate() {
    if (this.params.action && typeof this[this.params.action] === 'function') {
      this[this.params.action]();
    }
  }
}
```

I've written the above example with ES6 classes because it's less verbose, but this trivially maps to ES5.

If you want to mix this behavior into other controllers, you could extend this class.

**Comment by niemyjski** [comment]
Awesome, thanks for that.

On a side note: Is there any utility functions exposed to convert mark-fixed to markFixed (like how directives are resolved?) It would make it easier to call a function based on a friendly url.

**Comment by ewinslow** [comment]
IIUC, this sounds like it would be begging for cross-site-scripting attacks.

For example, imagine passing around this deceptively labeled link:

```html
<a href=".../issues/delete_them_all">See some cute kitties</a>
```

Actions should always require user interaction beyond navigating to the page...

**Comment by niemyjski** [comment]
You still have checks server side to see if they can do something /
prompt a dialog when the method is called to confirm the action...
It's just removing boilerplate..

On 1/16/15, Evan Winslow <notifications@github.com> wrote:
> IIUC, this sounds like it would be begging for cross-site-scripting
> attacks.
>
> For example, imagine passing around this deceptively labeled link:
>
> ```html
> <a href=".../issues/delete_them_all">See some cute kitties</a>
> ```
>
> Actions should always require user interaction beyond navigating to the
> page...
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/angular/router/issues/53#issuecomment-70346969


-- 
Thanks
-Blake Niemyjski

**Comment by ewinslow** [comment]
Server side checks are not going to save you here. XSS was not quite the right term. This is more similar to cross site request forgery. If an attacker can convince an unsuspecting user to click on a link that takes some destructive action,
then that is a security problem.

Throwing up a dialog to confirm the action would solve this issue.

**Comment by btford** [comment]
@ewinslow is correct. Any time you run code as the result of some navigation from a URL, you run this risk.

I'm not advocating this pattern, but I think it should be possible to implement at the application layer.

I think it's worth adding this to the router's documentation as a note on security.

**Comment by niemyjski** [comment]
Yes, I agree with you on security too. But that should be left up to the developer to implement a check/prompt client side.

**Comment by btford** [comment]
I'm going to close this since there are a variety of ways to implement it given the hooks exposed to controllers.

If this question comes up repeatedly, I'll add something about it to the documentation. For now, I think just being able to point devs with a similar question to this thread is good enough.

Thanks!
