### ISSUE TITLE
Problem setting up plunker for ngFuturisticRouter

### ISSUE THREAD

**Issue by SanderElias** [angular/router#60]
Wanted to create [a start-point](http://plnkr.co/edit/dqptSDHOpsoNBGuQJoJo?p=preview) to play around with the new router. 
I get a  ReferenceError: $traceurRuntime is not defined at Object.<anonymous> (https://rawgit.com/angular/router/master/dist/router.es5.js:867:4).

It looks like it's depending on the traceur runtime. Is this an oversight, or do I need to load the for-mentioned runtime?

**Comment by btford** [comment]
The latest build removes the runtime dependency.

I'll push an update to npm soon. :)

**Comment by SanderElias** [comment]
I was using https://rawgit.com/angular/router/master/dist/router.es5.js, Is that connected to npm?

**Comment by btford** [comment]
That file is generated on each release. Publishing a release to npm means
that file will also be updated.

**Comment by SanderElias** [comment]
And so we learn every day ;) thanks!

**Comment by btford** [comment]
I'm going to publish another release on Friday, so then I'll be able to close this. Thanks for being patient. :)

**Comment by btford** [comment]
Try now with v0.2.0. Should be much better.
