### ISSUE TITLE
example(1.x): building a custom UI component that uses routes

### ISSUE THREAD

**Issue by niemyjski** [angular/router#61]
One of the things missing from all angular router(s) docs is deeplinking to tab content. It would be awesome if this was in the new docs/sample as it's pretty common scenario with angular apps. 

Granted this may bring in an external dependency with the samples.

**Comment by btford** [comment]
"tab content?"

**Comment by niemyjski** [comment]
http://odetocode.com/blogs/scott/archive/2014/04/14/deep-linking-a-tabbed-ui-with-angularjs.aspx

**Comment by btford** [comment]
I'd re-phrase this as "building a custom UI component that uses routes." I do have an example of this in the works.

**Comment by niemyjski** [comment]
Thanks!

**Comment by btford** [comment]
Actually, I'm going to close this in favor of #47 since it's more actionable. I'll try to leave code comments in the implementation showing how to generalize.
