### ISSUE TITLE
chore(docs): parsing API docs from AtScript

### ISSUE THREAD

**Issue by btford** [angular/router#69]
I need to update the dgeni processors so that they can parse AtScript. Right now, the docs use esprima to grab the comments. This doesn't work for AtScript.

It looks like angular/angular has already solved this problem, so I should just grab and merge the configs as appropriate – https://github.com/angular/angular/tree/master/docs/dgeni-package

**Comment by btford** [comment]
@petebacondarwin – do you know if angular/angular has this yet?

**Comment by petebacondarwin** [comment]
Partially. Still needs work

**Comment by btford** [comment]
Okay. I don't need anything perfect, but I do need a way to grab API docs
from the AtScript portion and correlate them with the 1.x module. Maybe
just a regexp for now?

**Comment by petebacondarwin** [comment]
Some of this is in place in Angular 2 ...

This one pulls out the modules from a file: https://github.com/angular/angular/blob/master/docs/dgeni-package/processors/processModuleDocs.js

This one pulls out the classes from a module in a file https://github.com/angular/angular/blob/master/docs/dgeni-package/processors/processClassDocs.js
