### ISSUE TITLE
feat(1.x): pipeline API

### ISSUE THREAD

**Issue by btford** [angular/router#72]
Right now, most of the pipeline functionality lives in `router.navigate` in `router.ats`. I should move this out and expose the API to angular 1.x as a service.

This will make #44, #32, and #26 much easier.

**Comment by jgrund** [comment]
Would be great to have this. A generic middleware system a-la express would be great for this, as long as it handled location redirects without issue within the middleware stack.

**Comment by johnsonw** [comment]
+1, we're having to add a monkey-patch solution to add the concept of middleware in 1.3.

**Comment by btford** [comment]
This has since been implemented, but it needs better documentation.

**Comment by franleplant** [comment]
:+1:
