### ISSUE TITLE
chore(router): removing child routers

### ISSUE THREAD

**Issue by btford** [angular/router#76]

**Comment by schmitch** [comment]
Do you really want to remove Child Router?

**Comment by btford** [comment]
> Do you really want to remove Child Router?

I'm not sure exactly what the semantics should be; this issue is more a placeholder/reminder.

> Also i think there is a serious bug in there, since sometimes the url will get updated in the browser and right after that it will updated again to the previous route, but the browser still shows the content of the sub-route

Care to file a new issue with a reproduction à la [jsbin](http://jsbin.com/), [plnkr.co](http://plnkr.co), or [jsfiddle](http://jsfiddle.net/)?

**Comment by btford** [comment]
Addressed in 6d51f49f5d35554dcb4e51335f42d138a95498a3.
