### ISSUE TITLE
question(1.x): should service names begin with $?

### ISSUE THREAD

**Issue by btford** [angular/router#87]
In Angular 1.x, angular-provided services typically begin with a `$`.

**Comment by PascalPrecht** [comment]
I think it's the right way to go to name the `1.x` router `$router`. Even if it's clear that the router is actually a back port from `2.x` to `1.x`, where no `$` prefixes are used anymore, I don't think that people will be thankful if it follows yet another convention in `1.x`.

My 0.02£

**Comment by btford** [comment]
:+1:

**Comment by PascalPrecht** [comment]
We should then also change the name of `componentLoaderProvider` to `$componentLoaderProvider` accordingly.

**Comment by btford** [comment]
done, and available in `v0.3.0`, which I just published.

**Comment by PascalPrecht** [comment]
:+1:
